/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: ACHQyvh8il6C

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { LottieWrapper } from "@plasmicpkgs/lottie-react";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicDifferentiatorsCard.module.css"; // plasmic-import: ACHQyvh8il6C/css

import Icon56Icon from "./icons/PlasmicIcon__Icon56"; // plasmic-import: Qy8IRz6HF3N5/icon

createPlasmicElementProxy;

export type PlasmicDifferentiatorsCard__VariantMembers = {};
export type PlasmicDifferentiatorsCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicDifferentiatorsCard__VariantsArgs;
export const PlasmicDifferentiatorsCard__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDifferentiatorsCard__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicDifferentiatorsCard__ArgsType;
export const PlasmicDifferentiatorsCard__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicDifferentiatorsCard__OverridesType = {
  root?: Flex__<"div">;
  iconWrapper?: Flex__<"div">;
  titleWrapper?: Flex__<"div">;
  activeGridHoverStyle?: Flex__<"div">;
  lottie?: Flex__<typeof LottieWrapper>;
};

export interface DefaultDifferentiatorsCardProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDifferentiatorsCard__RenderFunc(props: {
  variants: PlasmicDifferentiatorsCard__VariantsArgs;
  args: PlasmicDifferentiatorsCard__ArgsType;
  overrides: PlasmicDifferentiatorsCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <div
        data-plasmic-name={"iconWrapper"}
        data-plasmic-override={overrides.iconWrapper}
        className={classNames(projectcss.all, sty.iconWrapper)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <Icon56Icon
              className={classNames(projectcss.all, sty.svg___6XkQ)}
              role={"img"}
            />
          ),

          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </div>
      <div
        data-plasmic-name={"titleWrapper"}
        data-plasmic-override={overrides.titleWrapper}
        className={classNames(projectcss.all, sty.titleWrapper)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nuOc6
              )}
            >
              {"Enter some text"}
            </div>
          ),
          value: args.slot,
          className: classNames(sty.slotTargetSlot)
        })}
      </div>
      <div
        data-plasmic-name={"activeGridHoverStyle"}
        data-plasmic-override={overrides.activeGridHoverStyle}
        className={classNames(projectcss.all, sty.activeGridHoverStyle)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__elRuO)} />

        <div className={classNames(projectcss.all, sty.freeBox___79Lio)}>
          <LottieWrapper
            data-plasmic-name={"lottie"}
            data-plasmic-override={overrides.lottie}
            animationData={{
              v: "4.10.1",
              fr: 30,
              ip: 0,
              op: 40,
              w: 80,
              h: 80,
              nm: "Success Checkmark",
              ddd: 0,
              assets: [],
              layers: [
                {
                  ddd: 0,
                  ind: 1,
                  ty: 4,
                  nm: "Check Mark",
                  sr: 1,
                  ks: {
                    o: { a: 0, k: 100, ix: 11 },
                    r: { a: 0, k: 0, ix: 10 },
                    p: { a: 0, k: [40, 40, 0], ix: 2 },
                    a: { a: 0, k: [-1.312, 6, 0], ix: 1 },
                    s: { a: 0, k: [100, 100, 100], ix: 6 }
                  },
                  ao: 0,
                  shapes: [
                    {
                      ty: "gr",
                      it: [
                        {
                          ind: 0,
                          ty: "sh",
                          ix: 1,
                          ks: {
                            a: 0,
                            k: {
                              i: [
                                [0, 0],
                                [0, 0],
                                [0, 0]
                              ],
                              o: [
                                [0, 0],
                                [0, 0],
                                [0, 0]
                              ],
                              v: [
                                [-15.75, 8],
                                [-8, 16],
                                [13.125, -4]
                              ],
                              c: false
                            },
                            ix: 2
                          },
                          nm: "Path 1",
                          mn: "ADBE Vector Shape - Group",
                          hd: false
                        },
                        {
                          ty: "tm",
                          s: {
                            a: 1,
                            k: [
                              {
                                i: { x: [0.667], y: [1] },
                                o: { x: [0.333], y: [0] },
                                n: ["0p667_1_0p333_0"],
                                t: 25,
                                s: [0],
                                e: [100]
                              },
                              { t: 33 }
                            ],
                            ix: 1
                          },
                          e: { a: 0, k: 0, ix: 2 },
                          o: { a: 0, k: 0, ix: 3 },
                          m: 1,
                          ix: 2,
                          nm: "Trim Paths 1",
                          mn: "ADBE Vector Filter - Trim",
                          hd: false
                        },
                        {
                          ty: "st",
                          c: { a: 0, k: [1, 1, 1, 1], ix: 3 },
                          o: { a: 0, k: 100, ix: 4 },
                          w: { a: 0, k: 3, ix: 5 },
                          lc: 2,
                          lj: 2,
                          nm: "Stroke 1",
                          mn: "ADBE Vector Graphic - Stroke",
                          hd: false
                        },
                        {
                          ty: "tr",
                          p: { a: 0, k: [0, 0], ix: 2 },
                          a: { a: 0, k: [0, 0], ix: 1 },
                          s: { a: 0, k: [100, 100], ix: 3 },
                          r: { a: 0, k: 0, ix: 6 },
                          o: { a: 0, k: 100, ix: 7 },
                          sk: { a: 0, k: 0, ix: 4 },
                          sa: { a: 0, k: 0, ix: 5 },
                          nm: "Transform"
                        }
                      ],
                      nm: "Shape 1",
                      np: 3,
                      cix: 2,
                      ix: 1,
                      mn: "ADBE Vector Group",
                      hd: false
                    }
                  ],
                  ip: 0,
                  op: 40,
                  st: 0,
                  bm: 0
                },
                {
                  ddd: 0,
                  ind: 2,
                  ty: 4,
                  nm: "Circle Flash",
                  sr: 1,
                  ks: {
                    o: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833], y: [0.833] },
                          o: { x: [0.167], y: [0.167] },
                          n: ["0p833_0p833_0p167_0p167"],
                          t: 25,
                          s: [0],
                          e: [98]
                        },
                        {
                          i: { x: [0.833], y: [0.833] },
                          o: { x: [0.167], y: [0.167] },
                          n: ["0p833_0p833_0p167_0p167"],
                          t: 30,
                          s: [98],
                          e: [0]
                        },
                        { t: 38 }
                      ],
                      ix: 11
                    },
                    r: { a: 0, k: 0, ix: 10 },
                    p: { a: 0, k: [40, 40, 0], ix: 2 },
                    a: { a: 0, k: [0, 0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                          o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                          n: [
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0"
                          ],
                          t: 25,
                          s: [0, 0, 100],
                          e: [100, 100, 100]
                        },
                        { t: 30 }
                      ],
                      ix: 6
                    }
                  },
                  ao: 0,
                  shapes: [
                    {
                      d: 1,
                      ty: "el",
                      s: { a: 0, k: [64, 64], ix: 2 },
                      p: { a: 0, k: [0, 0], ix: 3 },
                      nm: "Ellipse Path 1",
                      mn: "ADBE Vector Shape - Ellipse",
                      hd: false
                    },
                    {
                      ty: "fl",
                      c: {
                        a: 0,
                        k: [0.529866635799, 0.961458325386, 0.448091417551, 1],
                        ix: 4
                      },
                      o: { a: 0, k: 100, ix: 5 },
                      r: 1,
                      nm: "Fill 1",
                      mn: "ADBE Vector Graphic - Fill",
                      hd: false
                    }
                  ],
                  ip: 0,
                  op: 40,
                  st: 0,
                  bm: 0
                },
                {
                  ddd: 0,
                  ind: 3,
                  ty: 4,
                  nm: "Circle Stroke",
                  sr: 1,
                  ks: {
                    o: { a: 0, k: 100, ix: 11 },
                    r: { a: 0, k: 0, ix: 10 },
                    p: { a: 0, k: [39.022, 39.022, 0], ix: 2 },
                    a: { a: 0, k: [0, 0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                          o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                          n: [
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0"
                          ],
                          t: 16,
                          s: [100, 100, 100],
                          e: [80, 80, 100]
                        },
                        {
                          i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                          o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                          n: [
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0"
                          ],
                          t: 22,
                          s: [80, 80, 100],
                          e: [120, 120, 100]
                        },
                        {
                          i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                          o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                          n: [
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0"
                          ],
                          t: 25,
                          s: [120, 120, 100],
                          e: [100, 100, 100]
                        },
                        { t: 29 }
                      ],
                      ix: 6
                    }
                  },
                  ao: 0,
                  shapes: [
                    {
                      ty: "gr",
                      it: [
                        {
                          d: 1,
                          ty: "el",
                          s: { a: 0, k: [60, 60], ix: 2 },
                          p: { a: 0, k: [0, 0], ix: 3 },
                          nm: "Ellipse Path 1",
                          mn: "ADBE Vector Shape - Ellipse",
                          hd: false
                        },
                        {
                          ty: "tm",
                          s: {
                            a: 1,
                            k: [
                              {
                                i: { x: [0.667], y: [1] },
                                o: { x: [0.333], y: [0] },
                                n: ["0p667_1_0p333_0"],
                                t: 0,
                                s: [0],
                                e: [100]
                              },
                              { t: 16 }
                            ],
                            ix: 1
                          },
                          e: { a: 0, k: 0, ix: 2 },
                          o: { a: 0, k: 0, ix: 3 },
                          m: 1,
                          ix: 2,
                          nm: "Trim Paths 1",
                          mn: "ADBE Vector Filter - Trim",
                          hd: false
                        },
                        {
                          ty: "st",
                          c: {
                            a: 0,
                            k: [
                              0.427450984716, 0.800000011921, 0.35686275363, 1
                            ],
                            ix: 3
                          },
                          o: { a: 0, k: 100, ix: 4 },
                          w: { a: 0, k: 3, ix: 5 },
                          lc: 2,
                          lj: 2,
                          nm: "Stroke 1",
                          mn: "ADBE Vector Graphic - Stroke",
                          hd: false
                        },
                        {
                          ty: "tr",
                          p: { a: 0, k: [0.978, 0.978], ix: 2 },
                          a: { a: 0, k: [0, 0], ix: 1 },
                          s: { a: 0, k: [100, 100], ix: 3 },
                          r: { a: 0, k: 0, ix: 6 },
                          o: { a: 0, k: 100, ix: 7 },
                          sk: { a: 0, k: 0, ix: 4 },
                          sa: { a: 0, k: 0, ix: 5 },
                          nm: "Transform"
                        }
                      ],
                      nm: "Ellipse 1",
                      np: 3,
                      cix: 2,
                      ix: 1,
                      mn: "ADBE Vector Group",
                      hd: false
                    }
                  ],
                  ip: 0,
                  op: 40,
                  st: 0,
                  bm: 0
                },
                {
                  ddd: 0,
                  ind: 4,
                  ty: 4,
                  nm: "Circle Green Fill",
                  sr: 1,
                  ks: {
                    o: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833], y: [0.833] },
                          o: { x: [0.167], y: [0.167] },
                          n: ["0p833_0p833_0p167_0p167"],
                          t: 21,
                          s: [0],
                          e: [98]
                        },
                        { t: 28 }
                      ],
                      ix: 11
                    },
                    r: { a: 0, k: 0, ix: 10 },
                    p: { a: 0, k: [40, 40, 0], ix: 2 },
                    a: { a: 0, k: [0, 0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                          o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                          n: [
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0",
                            "0p667_1_0p333_0"
                          ],
                          t: 21,
                          s: [0, 0, 100],
                          e: [100, 100, 100]
                        },
                        { t: 28 }
                      ],
                      ix: 6
                    }
                  },
                  ao: 0,
                  shapes: [
                    {
                      d: 1,
                      ty: "el",
                      s: { a: 0, k: [64, 64], ix: 2 },
                      p: { a: 0, k: [0, 0], ix: 3 },
                      nm: "Ellipse Path 1",
                      mn: "ADBE Vector Shape - Ellipse",
                      hd: false
                    },
                    {
                      ty: "fl",
                      c: {
                        a: 0,
                        k: [0.427450984716, 0.800000011921, 0.35686275363, 1],
                        ix: 4
                      },
                      o: { a: 0, k: 100, ix: 5 },
                      r: 1,
                      nm: "Fill 1",
                      mn: "ADBE Vector Graphic - Fill",
                      hd: false
                    }
                  ],
                  ip: 0,
                  op: 40,
                  st: 0,
                  bm: 0
                }
              ]
            }}
            className={classNames("__wab_instance", sty.lottie)}
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "iconWrapper",
    "titleWrapper",
    "activeGridHoverStyle",
    "lottie"
  ],
  iconWrapper: ["iconWrapper"],
  titleWrapper: ["titleWrapper"],
  activeGridHoverStyle: ["activeGridHoverStyle", "lottie"],
  lottie: ["lottie"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  iconWrapper: "div";
  titleWrapper: "div";
  activeGridHoverStyle: "div";
  lottie: typeof LottieWrapper;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDifferentiatorsCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDifferentiatorsCard__VariantsArgs;
    args?: PlasmicDifferentiatorsCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDifferentiatorsCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDifferentiatorsCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDifferentiatorsCard__ArgProps,
          internalVariantPropNames: PlasmicDifferentiatorsCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDifferentiatorsCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDifferentiatorsCard";
  } else {
    func.displayName = `PlasmicDifferentiatorsCard.${nodeName}`;
  }
  return func;
}

export const PlasmicDifferentiatorsCard = Object.assign(
  // Top-level PlasmicDifferentiatorsCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iconWrapper: makeNodeComponent("iconWrapper"),
    titleWrapper: makeNodeComponent("titleWrapper"),
    activeGridHoverStyle: makeNodeComponent("activeGridHoverStyle"),
    lottie: makeNodeComponent("lottie"),

    // Metadata about props expected for PlasmicDifferentiatorsCard
    internalVariantProps: PlasmicDifferentiatorsCard__VariantProps,
    internalArgProps: PlasmicDifferentiatorsCard__ArgProps
  }
);

export default PlasmicDifferentiatorsCard;
/* prettier-ignore-end */
