/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: BPQllnOPF9Mf

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import GlobalShell from "../../GlobalShell"; // plasmic-import: VYweC3w_Jh99/component
import Section from "../../Section"; // plasmic-import: FaKfIdG9aMZc/component
import Hero from "../../Hero"; // plasmic-import: 6HGOGZ6Em2sv/component
import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import { ParallaxWrapper } from "@plasmicpkgs/react-scroll-parallax";
import ProjectEstimator from "../../ProjectEstimator"; // plasmic-import: oQ7EPrt8XMf2/component
import Logo from "../../Logo"; // plasmic-import: gC5_2888qYv4/component
import BookMeeting from "../../BookMeeting"; // plasmic-import: H-_o4Ye8qC3P/component
import Footer from "../../Footer"; // plasmic-import: XJ7-8nUHEe46/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicAiProjectEstimator.module.css"; // plasmic-import: BPQllnOPF9Mf/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: k4QR0HpbesmK/icon
import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: UosIBoZBJdWT/icon

createPlasmicElementProxy;

export type PlasmicAiProjectEstimator__VariantMembers = {};
export type PlasmicAiProjectEstimator__VariantsArgs = {};
type VariantPropType = keyof PlasmicAiProjectEstimator__VariantsArgs;
export const PlasmicAiProjectEstimator__VariantProps =
  new Array<VariantPropType>();

export type PlasmicAiProjectEstimator__ArgsType = {};
type ArgPropType = keyof PlasmicAiProjectEstimator__ArgsType;
export const PlasmicAiProjectEstimator__ArgProps = new Array<ArgPropType>();

export type PlasmicAiProjectEstimator__OverridesType = {
  root?: Flex__<"div">;
  globalShell?: Flex__<typeof GlobalShell>;
  hero?: Flex__<typeof Hero>;
  h1?: Flex__<"h1">;
  rock?: Flex__<typeof ParallaxWrapper>;
  field?: Flex__<typeof ParallaxWrapper>;
  astronaut?: Flex__<typeof ParallaxWrapper>;
  estimator?: Flex__<typeof Section>;
  h2?: Flex__<"h2">;
  projectEstimator?: Flex__<typeof ProjectEstimator>;
  scrollParallax?: Flex__<typeof ParallaxWrapper>;
  logo?: Flex__<typeof Logo>;
  bookMeeting?: Flex__<typeof BookMeeting>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultAiProjectEstimatorProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAiProjectEstimator__RenderFunc(props: {
  variants: PlasmicAiProjectEstimator__VariantsArgs;
  args: PlasmicAiProjectEstimator__ArgsType;
  overrides: PlasmicAiProjectEstimator__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicAiProjectEstimator.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicAiProjectEstimator.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <GlobalShell
            data-plasmic-name={"globalShell"}
            data-plasmic-override={overrides.globalShell}
            className={classNames("__wab_instance", sty.globalShell)}
            footerWrapper={
              <React.Fragment>
                <Section
                  backgroundDisabled={true}
                  bgImage={null}
                  className={classNames("__wab_instance", sty.section__dUtXl)}
                  sectionContent={
                    <BookMeeting
                      data-plasmic-name={"bookMeeting"}
                      data-plasmic-override={overrides.bookMeeting}
                      className={classNames("__wab_instance", sty.bookMeeting)}
                    />
                  }
                />

                <Footer
                  data-plasmic-name={"footer"}
                  data-plasmic-override={overrides.footer}
                  className={classNames("__wab_instance", sty.footer)}
                >
                  {"Don't fall into chaos..."}
                </Footer>
              </React.Fragment>
            }
            main={
              <React.Fragment>
                <Section
                  bgImage={
                    <React.Fragment>
                      <ParallaxWrapper
                        data-plasmic-name={"rock"}
                        data-plasmic-override={overrides.rock}
                        className={classNames("__wab_instance", sty.rock)}
                        speed={20}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__aaPzb)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "20vw"
                              : hasVariant(globalVariants, "screen", "tablet")
                                ? "15vw"
                                : "auto"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/hypernova_inc/images/adobeStock10340408361Png.png",
                            fullWidth: 168,
                            fullHeight: 178,
                            aspectRatio: undefined
                          }}
                        />
                      </ParallaxWrapper>
                      <ParallaxWrapper
                        data-plasmic-name={"field"}
                        data-plasmic-override={overrides.field}
                        className={classNames("__wab_instance", sty.field)}
                        speed={20}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__noEt)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/hypernova_inc/images/adobeStock802381366Png.png",
                            fullWidth: 4608,
                            fullHeight: 3072,
                            aspectRatio: undefined
                          }}
                        />
                      </ParallaxWrapper>
                      <ParallaxWrapper
                        data-plasmic-name={"astronaut"}
                        data-plasmic-override={overrides.astronaut}
                        className={classNames("__wab_instance", sty.astronaut)}
                        speed={20}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__x7TkB)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "70vw"
                              : hasVariant(globalVariants, "screen", "tablet")
                                ? "60vw"
                                : "30vw"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/hypernova_inc/images/astronautSittingPng3.png",
                            fullWidth: 644,
                            fullHeight: 896,
                            aspectRatio: undefined
                          }}
                        />
                      </ParallaxWrapper>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qkW4D)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/hypernova_inc/images/asteroidFieldBackgroundPng2.png",
                          fullWidth: 3136,
                          fullHeight: 2500,
                          aspectRatio: undefined
                        }}
                      />
                    </React.Fragment>
                  }
                  className={classNames("__wab_instance", sty.section__csKjF)}
                  sectionContent={
                    <Hero
                      data-plasmic-name={"hero"}
                      data-plasmic-override={overrides.hero}
                      className={classNames("__wab_instance", sty.hero)}
                      description={
                        "Use our AI Powered Project Estimation Tool to advance your concept. In just a few steps, you'll see recommendations for budget, team composition, timeline, and infrastructure for your project."
                      }
                      heading={
                        <h1
                          data-plasmic-name={"h1"}
                          data-plasmic-override={overrides.h1}
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {"State of the Art "}
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{
                                color: "var(--token-CtevabluNWTZ)",
                                fontWeight: 700
                              }}
                            >
                              {"Project Estimation"}
                            </span>
                          </React.Fragment>
                        </h1>
                      }
                      socialProofDisabled={true}
                      subheading={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xGnR7
                          )}
                        >
                          {"Senior Developers"}
                        </div>
                      }
                    >
                      <HypernovaLinkButton
                        destination={"#project-estimator"}
                        disabled={false}
                        iconPosition={"right"}
                        slot={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__viW8V
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__s4M5E
                          )}
                        >
                          {"Get an Instant Estimate"}
                        </div>
                      </HypernovaLinkButton>
                      <HypernovaLinkButton
                        color={"blueOutline"}
                        destination={`/book-a-meeting`}
                        disabled={false}
                        iconPosition={"none"}
                        slot={
                          <VectorSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__tbcNn
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xMvhU
                          )}
                        >
                          {"Book a meeting instead"}
                        </div>
                      </HypernovaLinkButton>
                    </Hero>
                  }
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox__imQbh, ``)}
                  id={"project-estimator"}
                >
                  <Section
                    data-plasmic-name={"estimator"}
                    data-plasmic-override={overrides.estimator}
                    backgroundDisabled={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : undefined
                    }
                    bgImage={
                      <ParallaxWrapper
                        data-plasmic-name={"scrollParallax"}
                        data-plasmic-override={overrides.scrollParallax}
                        className={classNames(
                          "__wab_instance",
                          sty.scrollParallax
                        )}
                        speed={55}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__rEi7C
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__bJsIo)}
                            displayHeight={"auto"}
                            displayMaxHeight={"1512px"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? "789px"
                                : "0"
                            }
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/hypernova_inc/images/astronautStationPng.png",
                              fullWidth: 1409,
                              fullHeight: 769,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </ParallaxWrapper>
                    }
                    className={classNames("__wab_instance", sty.estimator)}
                    fgImage={null}
                    h2={
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"AI Powered Project Estimator"}
                      </h2>
                    }
                    header={true}
                    padding={"_89PxIdFragment"}
                    sectionContent={
                      <ProjectEstimator
                        data-plasmic-name={"projectEstimator"}
                        data-plasmic-override={overrides.projectEstimator}
                        className={classNames(
                          "__wab_instance",
                          sty.projectEstimator
                        )}
                        step={"start"}
                      />
                    }
                    subheaderEnabled={true}
                    subheading={
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rrKAp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xqV7B
                          )}
                        >
                          {"Powered by"}
                        </div>
                        <Logo
                          data-plasmic-name={"logo"}
                          data-plasmic-override={overrides.logo}
                          className={classNames("__wab_instance", sty.logo)}
                          size={"extraSmall"}
                          type={"animatedDark"}
                        />
                      </div>
                    }
                  />
                </div>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "globalShell",
    "hero",
    "h1",
    "rock",
    "field",
    "astronaut",
    "estimator",
    "h2",
    "projectEstimator",
    "scrollParallax",
    "logo",
    "bookMeeting",
    "footer"
  ],
  globalShell: [
    "globalShell",
    "hero",
    "h1",
    "rock",
    "field",
    "astronaut",
    "estimator",
    "h2",
    "projectEstimator",
    "scrollParallax",
    "logo",
    "bookMeeting",
    "footer"
  ],
  hero: ["hero", "h1"],
  h1: ["h1"],
  rock: ["rock"],
  field: ["field"],
  astronaut: ["astronaut"],
  estimator: ["estimator", "h2", "projectEstimator", "scrollParallax", "logo"],
  h2: ["h2"],
  projectEstimator: ["projectEstimator"],
  scrollParallax: ["scrollParallax"],
  logo: ["logo"],
  bookMeeting: ["bookMeeting"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  globalShell: typeof GlobalShell;
  hero: typeof Hero;
  h1: "h1";
  rock: typeof ParallaxWrapper;
  field: typeof ParallaxWrapper;
  astronaut: typeof ParallaxWrapper;
  estimator: typeof Section;
  h2: "h2";
  projectEstimator: typeof ProjectEstimator;
  scrollParallax: typeof ParallaxWrapper;
  logo: typeof Logo;
  bookMeeting: typeof BookMeeting;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAiProjectEstimator__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAiProjectEstimator__VariantsArgs;
    args?: PlasmicAiProjectEstimator__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAiProjectEstimator__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAiProjectEstimator__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAiProjectEstimator__ArgProps,
          internalVariantPropNames: PlasmicAiProjectEstimator__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAiProjectEstimator__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAiProjectEstimator";
  } else {
    func.displayName = `PlasmicAiProjectEstimator.${nodeName}`;
  }
  return func;
}

export const PlasmicAiProjectEstimator = Object.assign(
  // Top-level PlasmicAiProjectEstimator renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    globalShell: makeNodeComponent("globalShell"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    rock: makeNodeComponent("rock"),
    field: makeNodeComponent("field"),
    astronaut: makeNodeComponent("astronaut"),
    estimator: makeNodeComponent("estimator"),
    h2: makeNodeComponent("h2"),
    projectEstimator: makeNodeComponent("projectEstimator"),
    scrollParallax: makeNodeComponent("scrollParallax"),
    logo: makeNodeComponent("logo"),
    bookMeeting: makeNodeComponent("bookMeeting"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicAiProjectEstimator
    internalVariantProps: PlasmicAiProjectEstimator__VariantProps,
    internalArgProps: PlasmicAiProjectEstimator__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/e6d668f661a8bbb74ec3250c517498eb.png",
      canonical: ""
    }
  }
);

export default PlasmicAiProjectEstimator;
/* prettier-ignore-end */
