/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: Piboua9vW5I-

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicFooterSlotted.module.css"; // plasmic-import: Piboua9vW5I-/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: k4QR0HpbesmK/icon

createPlasmicElementProxy;

export type PlasmicFooterSlotted__VariantMembers = {
  design: "realTeam";
};
export type PlasmicFooterSlotted__VariantsArgs = {
  design?: SingleChoiceArg<"realTeam">;
};
type VariantPropType = keyof PlasmicFooterSlotted__VariantsArgs;
export const PlasmicFooterSlotted__VariantProps = new Array<VariantPropType>(
  "design"
);

export type PlasmicFooterSlotted__ArgsType = { footerCard?: React.ReactNode };
type ArgPropType = keyof PlasmicFooterSlotted__ArgsType;
export const PlasmicFooterSlotted__ArgProps = new Array<ArgPropType>(
  "footerCard"
);

export type PlasmicFooterSlotted__OverridesType = {
  root?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultFooterSlottedProps {
  footerCard?: React.ReactNode;
  design?: SingleChoiceArg<"realTeam">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooterSlotted__RenderFunc(props: {
  variants: PlasmicFooterSlotted__VariantsArgs;
  args: PlasmicFooterSlotted__ArgsType;
  overrides: PlasmicFooterSlotted__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "design",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.design
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootdesign_realTeam]: hasVariant($state, "design", "realTeam") }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__qk6Ec)}>
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__uvo4, {
            [sty.imgdesign_realTeam__uvo41Uz3T]: hasVariant(
              $state,
              "design",
              "realTeam"
            )
          })}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: "/plasmic/hypernova_inc/images/_2916Fed7D99Ed100857866Cfd9909A93117Dde1E1Png3.png",
            fullWidth: 2048,
            fullHeight: 1168,
            aspectRatio: undefined
          }}
        />
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___7OAQq)}>
        {renderPlasmicSlot({
          defaultContents: (
            <div className={classNames(projectcss.all, sty.freeBox__wdIkb)}>
              <div className={classNames(projectcss.all, sty.freeBox__yrSGb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lOoEo
                  )}
                >
                  {"Don't fall into chaos."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c0RqE
                  )}
                >
                  {"Engineer with hypernova."}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__bd9Fm)}>
                <HypernovaLinkButton
                  className={classNames(
                    "__wab_instance",
                    sty.hypernovaLinkButton__usq7B
                  )}
                  slot={null}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6ZHFg
                    )}
                  >
                    {"Start Your Project"}
                  </div>
                  <IconIcon
                    className={classNames(projectcss.all, sty.svg___2173B)}
                    role={"img"}
                  />
                </HypernovaLinkButton>
              </div>
            </div>
          ),
          value: args.footerCard
        })}
        <div className={classNames(projectcss.all, sty.freeBox__gQpO)}>
          <div className={classNames(projectcss.all, sty.freeBox__muqgR)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__uEtzE)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hypernova_inc/images/darkLogo.svg",
                fullWidth: 177,
                fullHeight: 41,
                aspectRatio: undefined
              }}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__iA80)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {"\u00a9 Copyright Hypernova USA   |   All Rights Reserved"}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterSlotted__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterSlotted__VariantsArgs;
    args?: PlasmicFooterSlotted__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFooterSlotted__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFooterSlotted__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooterSlotted__ArgProps,
          internalVariantPropNames: PlasmicFooterSlotted__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooterSlotted__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterSlotted";
  } else {
    func.displayName = `PlasmicFooterSlotted.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterSlotted = Object.assign(
  // Top-level PlasmicFooterSlotted renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicFooterSlotted
    internalVariantProps: PlasmicFooterSlotted__VariantProps,
    internalArgProps: PlasmicFooterSlotted__ArgProps
  }
);

export default PlasmicFooterSlotted;
/* prettier-ignore-end */
