/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: usHrmf5rDqG3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import GlobalShell from "../../GlobalShell"; // plasmic-import: VYweC3w_Jh99/component
import Section from "../../Section"; // plasmic-import: FaKfIdG9aMZc/component
import Hero from "../../Hero"; // plasmic-import: 6HGOGZ6Em2sv/component
import HypernovaNoFollowButton from "../../HypernovaNoFollowButton"; // plasmic-import: wNvdxBdGEsIv/component
import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import { ParallaxWrapper } from "@plasmicpkgs/react-scroll-parallax";
import BookMeeting from "../../BookMeeting"; // plasmic-import: H-_o4Ye8qC3P/component
import Footer from "../../Footer"; // plasmic-import: XJ7-8nUHEe46/component
import MeetingModalOverlay from "../../MeetingModalOverlay"; // plasmic-import: pmJL4qp2O_wN/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicBookAMeeting.module.css"; // plasmic-import: usHrmf5rDqG3/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: k4QR0HpbesmK/icon
import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: UosIBoZBJdWT/icon

createPlasmicElementProxy;

export type PlasmicBookAMeeting__VariantMembers = {
  bookMeeting: "bookMeeting";
};
export type PlasmicBookAMeeting__VariantsArgs = {
  bookMeeting?: SingleBooleanChoiceArg<"bookMeeting">;
};
type VariantPropType = keyof PlasmicBookAMeeting__VariantsArgs;
export const PlasmicBookAMeeting__VariantProps = new Array<VariantPropType>(
  "bookMeeting"
);

export type PlasmicBookAMeeting__ArgsType = {};
type ArgPropType = keyof PlasmicBookAMeeting__ArgsType;
export const PlasmicBookAMeeting__ArgProps = new Array<ArgPropType>();

export type PlasmicBookAMeeting__OverridesType = {
  root?: Flex__<"div">;
  globalShell?: Flex__<typeof GlobalShell>;
  hero?: Flex__<typeof Hero>;
  h1?: Flex__<"h1">;
  hypernovaNoFollowButton?: Flex__<typeof HypernovaNoFollowButton>;
  hypernovaLinkButton?: Flex__<typeof HypernovaLinkButton>;
  freeBox?: Flex__<"div">;
  astronautKneeling?: Flex__<typeof ParallaxWrapper>;
  spaceRock?: Flex__<typeof ParallaxWrapper>;
  h2?: Flex__<"h2">;
  bookMeeting?: Flex__<typeof BookMeeting>;
  footer?: Flex__<typeof Footer>;
  meetingModalOverlay?: Flex__<typeof MeetingModalOverlay>;
};

export interface DefaultBookAMeetingProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBookAMeeting__RenderFunc(props: {
  variants: PlasmicBookAMeeting__VariantsArgs;
  args: PlasmicBookAMeeting__ArgsType;
  overrides: PlasmicBookAMeeting__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "bookMeeting",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.bookMeeting
      },
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicBookAMeeting.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicBookAMeeting.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root,
            {
              [sty.rootbookMeeting]: hasVariant(
                $state,
                "bookMeeting",
                "bookMeeting"
              )
            }
          )}
        >
          <GlobalShell
            data-plasmic-name={"globalShell"}
            data-plasmic-override={overrides.globalShell}
            className={classNames("__wab_instance", sty.globalShell, {
              [sty.globalShellbookMeeting]: hasVariant(
                $state,
                "bookMeeting",
                "bookMeeting"
              )
            })}
            footerWrapper={
              <Footer
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                className={classNames("__wab_instance", sty.footer)}
                slot={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x14CT
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Engineer with "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"hypernova"}
                      </span>
                      <React.Fragment>{"."}</React.Fragment>
                    </React.Fragment>
                  </div>
                }
              >
                {"Don't fall into chaos..."}
              </Footer>
            }
            main={
              <React.Fragment>
                <Section
                  bgImage={
                    <React.Fragment>
                      <div
                        data-plasmic-name={"freeBox"}
                        data-plasmic-override={overrides.freeBox}
                        className={classNames(projectcss.all, sty.freeBox)}
                      >
                        <ParallaxWrapper
                          data-plasmic-name={"astronautKneeling"}
                          data-plasmic-override={overrides.astronautKneeling}
                          className={classNames(
                            "__wab_instance",
                            sty.astronautKneeling
                          )}
                          speed={20}
                        >
                          {false ? (
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__ze2Oe)}
                              displayHeight={"60vh"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={
                                hasVariant(globalVariants, "screen", "tablet")
                                  ? "100%"
                                  : "auto"
                              }
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/hypernova_inc/images/adobeStock802381366Png.png",
                                fullWidth: 4608,
                                fullHeight: 3072,
                                aspectRatio: undefined
                              }}
                            />
                          ) : null}
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___6X10)}
                            displayHeight={"100%"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? "90vw"
                                : hasVariant(globalVariants, "screen", "tablet")
                                  ? "75vw"
                                  : "30vw"
                            }
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/hypernova_inc/images/touchdownPng.png",
                              fullWidth: 2000,
                              fullHeight: 1500,
                              aspectRatio: undefined
                            }}
                          />
                        </ParallaxWrapper>
                      </div>
                      <ParallaxWrapper
                        data-plasmic-name={"spaceRock"}
                        data-plasmic-override={overrides.spaceRock}
                        className={classNames("__wab_instance", sty.spaceRock)}
                        speed={10}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__ujdoO)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"9vw"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/hypernova_inc/images/adobeStock10340408361Png.png",
                            fullWidth: 168,
                            fullHeight: 178,
                            aspectRatio: undefined
                          }}
                        />
                      </ParallaxWrapper>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__a5KCw)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/hypernova_inc/images/atmosphereBackgroundPng2.png",
                          fullWidth: 937,
                          fullHeight: 605,
                          aspectRatio: undefined
                        }}
                      />
                    </React.Fragment>
                  }
                  className={classNames("__wab_instance", sty.section__ulJ0H)}
                  sectionContent={
                    <Hero
                      data-plasmic-name={"hero"}
                      data-plasmic-override={overrides.hero}
                      className={classNames("__wab_instance", sty.hero)}
                      description={
                        "Let\u2019s turn your vision into a high-performing digital experience. Tell us about your project, and we\u2019ll take it from there!"
                      }
                      heading={
                        <h1
                          data-plasmic-name={"h1"}
                          data-plasmic-override={overrides.h1}
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {"Turn Your Roadmap \nInto "}
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-CtevabluNWTZ)" }}
                            >
                              {"Reality"}
                            </span>
                          </React.Fragment>
                        </h1>
                      }
                      socialProofDisabled={true}
                      subheading={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uvQ1Q
                          )}
                        >
                          {"Senior Developers"}
                        </div>
                      }
                    >
                      <HypernovaNoFollowButton
                        data-plasmic-name={"hypernovaNoFollowButton"}
                        data-plasmic-override={
                          overrides.hypernovaNoFollowButton
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.hypernovaNoFollowButton
                        )}
                        disabled={false}
                        iconPosition={"right"}
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateBookMeeting"] = true
                            ? (() => {
                                const actionArgs = {
                                  vgroup: "bookMeeting",
                                  operation: 4,
                                  value: "bookMeeting"
                                };
                                return (({ vgroup, value }) => {
                                  if (typeof value === "string") {
                                    value = [value];
                                  }

                                  $stateSet($state, vgroup, true);
                                  return true;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateBookMeeting"] != null &&
                            typeof $steps["updateBookMeeting"] === "object" &&
                            typeof $steps["updateBookMeeting"].then ===
                              "function"
                          ) {
                            $steps["updateBookMeeting"] =
                              await $steps["updateBookMeeting"];
                          }
                        }}
                        slot={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___0Pdsb
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Book a meeting now"}
                      </HypernovaNoFollowButton>
                      <HypernovaLinkButton
                        data-plasmic-name={"hypernovaLinkButton"}
                        data-plasmic-override={overrides.hypernovaLinkButton}
                        color={"blueOutline"}
                        destination={"#contact-us"}
                        disabled={false}
                        iconPosition={"none"}
                        slot={
                          <VectorSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__poTto
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9P1Q
                          )}
                        >
                          {"Contact Us"}
                        </div>
                      </HypernovaLinkButton>
                    </Hero>
                  }
                />

                <section
                  className={classNames(projectcss.all, sty.section__iZzri)}
                  id={"contact-us"}
                >
                  <Section
                    className={classNames(
                      "__wab_instance",
                      sty.section__hTbMc,
                      {
                        [sty.sectionbookMeeting__hTbMc3AfNa]: hasVariant(
                          $state,
                          "bookMeeting",
                          "bookMeeting"
                        )
                      }
                    )}
                    contentWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "full"
                        : undefined
                    }
                    h2={
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"Contact us"}
                      </h2>
                    }
                    header={true}
                    padding={"_89PxIdFragment"}
                    sectionContent={
                      <BookMeeting
                        data-plasmic-name={"bookMeeting"}
                        data-plasmic-override={overrides.bookMeeting}
                        className={classNames(
                          "__wab_instance",
                          sty.bookMeeting
                        )}
                      />
                    }
                  />
                </section>
              </React.Fragment>
            }
          />

          <MeetingModalOverlay
            data-plasmic-name={"meetingModalOverlay"}
            data-plasmic-override={overrides.meetingModalOverlay}
            active={
              hasVariant($state, "bookMeeting", "bookMeeting") &&
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? true
                : hasVariant($state, "bookMeeting", "bookMeeting") &&
                    hasVariant(globalVariants, "screen", "tablet")
                  ? true
                  : hasVariant($state, "bookMeeting", "bookMeeting")
                    ? true
                    : undefined
            }
            className={classNames("__wab_instance", sty.meetingModalOverlay, {
              [sty.meetingModalOverlaybookMeeting]: hasVariant(
                $state,
                "bookMeeting",
                "bookMeeting"
              )
            })}
            onClickClose={async event => {
              const $steps = {};

              $steps["updateBookMeeting"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "bookMeeting",
                      operation: 6,
                      value: "bookMeeting"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      $stateSet($state, vgroup, false);
                      return false;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateBookMeeting"] != null &&
                typeof $steps["updateBookMeeting"] === "object" &&
                typeof $steps["updateBookMeeting"].then === "function"
              ) {
                $steps["updateBookMeeting"] = await $steps["updateBookMeeting"];
              }
            }}
            onClickOverlay={async event => {
              const $steps = {};

              $steps["updateBookMeeting"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "bookMeeting",
                      operation: 6,
                      value: "bookMeeting"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      $stateSet($state, vgroup, false);
                      return false;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateBookMeeting"] != null &&
                typeof $steps["updateBookMeeting"] === "object" &&
                typeof $steps["updateBookMeeting"].then === "function"
              ) {
                $steps["updateBookMeeting"] = await $steps["updateBookMeeting"];
              }
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "globalShell",
    "hero",
    "h1",
    "hypernovaNoFollowButton",
    "hypernovaLinkButton",
    "freeBox",
    "astronautKneeling",
    "spaceRock",
    "h2",
    "bookMeeting",
    "footer",
    "meetingModalOverlay"
  ],
  globalShell: [
    "globalShell",
    "hero",
    "h1",
    "hypernovaNoFollowButton",
    "hypernovaLinkButton",
    "freeBox",
    "astronautKneeling",
    "spaceRock",
    "h2",
    "bookMeeting",
    "footer"
  ],
  hero: ["hero", "h1", "hypernovaNoFollowButton", "hypernovaLinkButton"],
  h1: ["h1"],
  hypernovaNoFollowButton: ["hypernovaNoFollowButton"],
  hypernovaLinkButton: ["hypernovaLinkButton"],
  freeBox: ["freeBox", "astronautKneeling"],
  astronautKneeling: ["astronautKneeling"],
  spaceRock: ["spaceRock"],
  h2: ["h2"],
  bookMeeting: ["bookMeeting"],
  footer: ["footer"],
  meetingModalOverlay: ["meetingModalOverlay"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  globalShell: typeof GlobalShell;
  hero: typeof Hero;
  h1: "h1";
  hypernovaNoFollowButton: typeof HypernovaNoFollowButton;
  hypernovaLinkButton: typeof HypernovaLinkButton;
  freeBox: "div";
  astronautKneeling: typeof ParallaxWrapper;
  spaceRock: typeof ParallaxWrapper;
  h2: "h2";
  bookMeeting: typeof BookMeeting;
  footer: typeof Footer;
  meetingModalOverlay: typeof MeetingModalOverlay;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBookAMeeting__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBookAMeeting__VariantsArgs;
    args?: PlasmicBookAMeeting__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicBookAMeeting__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicBookAMeeting__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBookAMeeting__ArgProps,
          internalVariantPropNames: PlasmicBookAMeeting__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBookAMeeting__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBookAMeeting";
  } else {
    func.displayName = `PlasmicBookAMeeting.${nodeName}`;
  }
  return func;
}

export const PlasmicBookAMeeting = Object.assign(
  // Top-level PlasmicBookAMeeting renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    globalShell: makeNodeComponent("globalShell"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    hypernovaNoFollowButton: makeNodeComponent("hypernovaNoFollowButton"),
    hypernovaLinkButton: makeNodeComponent("hypernovaLinkButton"),
    freeBox: makeNodeComponent("freeBox"),
    astronautKneeling: makeNodeComponent("astronautKneeling"),
    spaceRock: makeNodeComponent("spaceRock"),
    h2: makeNodeComponent("h2"),
    bookMeeting: makeNodeComponent("bookMeeting"),
    footer: makeNodeComponent("footer"),
    meetingModalOverlay: makeNodeComponent("meetingModalOverlay"),

    // Metadata about props expected for PlasmicBookAMeeting
    internalVariantProps: PlasmicBookAMeeting__VariantProps,
    internalArgProps: PlasmicBookAMeeting__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/34e4f29e602541c21c4a944ba93bd2da.png",
      canonical: ""
    }
  }
);

export default PlasmicBookAMeeting;
/* prettier-ignore-end */
