/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: pP59VKsofvxU

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicInfrastructureCard.module.css"; // plasmic-import: pP59VKsofvxU/css

createPlasmicElementProxy;

export type PlasmicInfrastructureCard__VariantMembers = {
  type: "staticVm" | "awsEphemeralArchitecture" | "kubernetes";
  selected: "selected";
};
export type PlasmicInfrastructureCard__VariantsArgs = {
  type?: SingleChoiceArg<
    "staticVm" | "awsEphemeralArchitecture" | "kubernetes"
  >;
  selected?: SingleBooleanChoiceArg<"selected">;
};
type VariantPropType = keyof PlasmicInfrastructureCard__VariantsArgs;
export const PlasmicInfrastructureCard__VariantProps =
  new Array<VariantPropType>("type", "selected");

export type PlasmicInfrastructureCard__ArgsType = {};
type ArgPropType = keyof PlasmicInfrastructureCard__ArgsType;
export const PlasmicInfrastructureCard__ArgProps = new Array<ArgPropType>();

export type PlasmicInfrastructureCard__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  text?: Flex__<"div">;
};

export interface DefaultInfrastructureCardProps {
  type?: SingleChoiceArg<
    "staticVm" | "awsEphemeralArchitecture" | "kubernetes"
  >;
  selected?: SingleBooleanChoiceArg<"selected">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInfrastructureCard__RenderFunc(props: {
  variants: PlasmicInfrastructureCard__VariantsArgs;
  args: PlasmicInfrastructureCard__ArgsType;
  overrides: PlasmicInfrastructureCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "type",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.type
      },
      {
        path: "selected",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.selected
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootselected]: hasVariant($state, "selected", "selected"),
          [sty.roottype_awsEphemeralArchitecture]: hasVariant(
            $state,
            "type",
            "awsEphemeralArchitecture"
          ),
          [sty.roottype_kubernetes]: hasVariant($state, "type", "kubernetes"),
          [sty.roottype_staticVm]: hasVariant($state, "type", "staticVm")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxselected]: hasVariant($state, "selected", "selected"),
          [sty.freeBoxtype_awsEphemeralArchitecture]: hasVariant(
            $state,
            "type",
            "awsEphemeralArchitecture"
          )
        })}
      >
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img, {
            [sty.imgtype_awsEphemeralArchitecture]: hasVariant(
              $state,
              "type",
              "awsEphemeralArchitecture"
            ),
            [sty.imgtype_staticVm]: hasVariant($state, "type", "staticVm")
          })}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"auto"}
          loading={"lazy"}
          src={
            hasVariant($state, "type", "awsEphemeralArchitecture")
              ? {
                  src: "/plasmic/hypernova_inc/images/image2.svg",
                  fullWidth: 36,
                  fullHeight: 21,
                  aspectRatio: undefined
                }
              : hasVariant($state, "type", "staticVm")
                ? {
                    src: "/plasmic/hypernova_inc/images/image3.svg",
                    fullWidth: 36,
                    fullHeight: 36,
                    aspectRatio: undefined
                  }
                : {
                    src: "/plasmic/hypernova_inc/images/image.svg",
                    fullWidth: 36,
                    fullHeight: 35,
                    aspectRatio: undefined
                  }
          }
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text,
            {
              [sty.textselected]: hasVariant($state, "selected", "selected"),
              [sty.texttype_awsEphemeralArchitecture]: hasVariant(
                $state,
                "type",
                "awsEphemeralArchitecture"
              ),
              [sty.texttype_kubernetes]: hasVariant(
                $state,
                "type",
                "kubernetes"
              ),
              [sty.texttype_staticVm]: hasVariant($state, "type", "staticVm")
            }
          )}
        >
          {hasVariant($state, "type", "kubernetes")
            ? "Kubernetes Cluster (Enterprise Apps)"
            : hasVariant($state, "type", "awsEphemeralArchitecture")
              ? "AWS Ephemeral Architecture (Scalable SaaS)"
              : hasVariant($state, "type", "staticVm")
                ? "Static Virtual Machine (MVPs, or Micro Apps)"
                : "Infrastructure"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "img", "text"],
  freeBox: ["freeBox", "img", "text"],
  img: ["img"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  img: typeof PlasmicImg__;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInfrastructureCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInfrastructureCard__VariantsArgs;
    args?: PlasmicInfrastructureCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicInfrastructureCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicInfrastructureCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicInfrastructureCard__ArgProps,
          internalVariantPropNames: PlasmicInfrastructureCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicInfrastructureCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInfrastructureCard";
  } else {
    func.displayName = `PlasmicInfrastructureCard.${nodeName}`;
  }
  return func;
}

export const PlasmicInfrastructureCard = Object.assign(
  // Top-level PlasmicInfrastructureCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicInfrastructureCard
    internalVariantProps: PlasmicInfrastructureCard__VariantProps,
    internalArgProps: PlasmicInfrastructureCard__ArgProps
  }
);

export default PlasmicInfrastructureCard;
/* prettier-ignore-end */
