/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: 6HGOGZ6Em2sv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicHero.module.css"; // plasmic-import: 6HGOGZ6Em2sv/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: k4QR0HpbesmK/icon
import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: UosIBoZBJdWT/icon

createPlasmicElementProxy;

export type PlasmicHero__VariantMembers = {
  socialProofDisabled: "socialProofDisabled";
  align: "left";
  subheadingDisabled: "subheadingDisabled";
  buttonsDisabled: "buttonsDisabled";
};
export type PlasmicHero__VariantsArgs = {
  socialProofDisabled?: SingleBooleanChoiceArg<"socialProofDisabled">;
  align?: SingleChoiceArg<"left">;
  subheadingDisabled?: SingleBooleanChoiceArg<"subheadingDisabled">;
  buttonsDisabled?: SingleBooleanChoiceArg<"buttonsDisabled">;
};
type VariantPropType = keyof PlasmicHero__VariantsArgs;
export const PlasmicHero__VariantProps = new Array<VariantPropType>(
  "socialProofDisabled",
  "align",
  "subheadingDisabled",
  "buttonsDisabled"
);

export type PlasmicHero__ArgsType = {
  heading?: React.ReactNode;
  subheading?: React.ReactNode;
  description?: React.ReactNode;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHero__ArgsType;
export const PlasmicHero__ArgProps = new Array<ArgPropType>(
  "heading",
  "subheading",
  "description",
  "children"
);

export type PlasmicHero__OverridesType = {
  sectionHero?: Flex__<"div">;
  content?: Flex__<"div">;
  social?: Flex__<"div">;
};

export interface DefaultHeroProps {
  heading?: React.ReactNode;
  subheading?: React.ReactNode;
  description?: React.ReactNode;
  children?: React.ReactNode;
  socialProofDisabled?: SingleBooleanChoiceArg<"socialProofDisabled">;
  align?: SingleChoiceArg<"left">;
  subheadingDisabled?: SingleBooleanChoiceArg<"subheadingDisabled">;
  buttonsDisabled?: SingleBooleanChoiceArg<"buttonsDisabled">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHero__RenderFunc(props: {
  variants: PlasmicHero__VariantsArgs;
  args: PlasmicHero__ArgsType;
  overrides: PlasmicHero__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "socialProofDisabled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props.socialProofDisabled
      },
      {
        path: "align",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.align
      },
      {
        path: "subheadingDisabled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props.subheadingDisabled
      },
      {
        path: "buttonsDisabled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.buttonsDisabled
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"sectionHero"}
      data-plasmic-override={overrides.sectionHero}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.sectionHero,
        {
          [sty.sectionHeroalign_left]: hasVariant($state, "align", "left"),
          [sty.sectionHerobuttonsDisabled]: hasVariant(
            $state,
            "buttonsDisabled",
            "buttonsDisabled"
          ),
          [sty.sectionHerosocialProofDisabled]: hasVariant(
            $state,
            "socialProofDisabled",
            "socialProofDisabled"
          ),
          [sty.sectionHerosubheadingDisabled]: hasVariant(
            $state,
            "subheadingDisabled",
            "subheadingDisabled"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"content"}
        data-plasmic-override={overrides.content}
        className={classNames(projectcss.all, sty.content, {
          [sty.contentalign_left]: hasVariant($state, "align", "left"),
          [sty.contentbuttonsDisabled]: hasVariant(
            $state,
            "buttonsDisabled",
            "buttonsDisabled"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__ffNnn, {
            [sty.freeBoxalign_left__ffNnnEi5RM]: hasVariant(
              $state,
              "align",
              "left"
            ),
            [sty.freeBoxsubheadingDisabled__ffNnnXaQz8]: hasVariant(
              $state,
              "subheadingDisabled",
              "subheadingDisabled"
            )
          })}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__pmfU5, {
              [sty.freeBoxalign_left__pmfU5Ei5RM]: hasVariant(
                $state,
                "align",
                "left"
              )
            })}
          >
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                sty.h1__mcPkX,
                {
                  [sty.h1align_left__mcPkXEi5RM]: hasVariant(
                    $state,
                    "align",
                    "left"
                  )
                }
              )}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jafJh
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {"Your Software, Built by "}
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-CtevabluNWTZ)" }}
                      >
                        {"AI-Enhanced"}
                      </span>
                    </React.Fragment>
                  </div>
                ),
                value: args.heading,
                className: classNames(sty.slotTargetHeading, {
                  [sty.slotTargetHeadingalign_left]: hasVariant(
                    $state,
                    "align",
                    "left"
                  )
                })
              })}
            </h1>
            {(
              hasVariant($state, "subheadingDisabled", "subheadingDisabled")
                ? false
                : true
            ) ? (
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  sty.h1___3V75E,
                  {
                    [sty.h1align_left___3V75EEi5RM]: hasVariant(
                      $state,
                      "align",
                      "left"
                    ),
                    [sty.h1subheadingDisabled___3V75ExaQz8]: hasVariant(
                      $state,
                      "subheadingDisabled",
                      "subheadingDisabled"
                    )
                  }
                )}
              >
                {renderPlasmicSlot({
                  defaultContents: (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iRaq0
                      )}
                    >
                      {"Senior Developers"}
                    </div>
                  ),
                  value: args.subheading,
                  className: classNames(sty.slotTargetSubheading, {
                    [sty.slotTargetSubheadingalign_left]: hasVariant(
                      $state,
                      "align",
                      "left"
                    )
                  })
                })}
              </h1>
            ) : null}
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__fq6RV, {
              [sty.freeBoxalign_left__fq6RVEi5RM]: hasVariant(
                $state,
                "align",
                "left"
              )
            })}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__tjIsa, {
                [sty.freeBoxalign_left__tjIsaEi5RM]: hasVariant(
                  $state,
                  "align",
                  "left"
                )
              })}
            >
              {renderPlasmicSlot({
                defaultContents:
                  "We combine human expertise with AI-driven efficiency to build enterprise-grade software that scales\u2014without the overhead \nof an in-house team.",
                value: args.description,
                className: classNames(sty.slotTargetDescription, {
                  [sty.slotTargetDescriptionalign_left]: hasVariant(
                    $state,
                    "align",
                    "left"
                  )
                })
              })}
            </div>
          </div>
        </div>
        {(
          hasVariant($state, "buttonsDisabled", "buttonsDisabled")
            ? false
            : true
        ) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__sjM0C, {
              [sty.freeBoxalign_left__sjM0CEi5RM]: hasVariant(
                $state,
                "align",
                "left"
              ),
              [sty.freeBoxbuttonsDisabled__sjM0CmZav]: hasVariant(
                $state,
                "buttonsDisabled",
                "buttonsDisabled"
              ),
              [sty.freeBoxsocialProofDisabled__sjM0CrLnwf]: hasVariant(
                $state,
                "socialProofDisabled",
                "socialProofDisabled"
              )
            })}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <HypernovaLinkButton
                    destination={`/book-a-meeting`}
                    disabled={false}
                    iconPosition={"right"}
                    slot={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___6VYa9)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gMr4Q
                      )}
                    >
                      {"Get Started"}
                    </div>
                  </HypernovaLinkButton>
                  <HypernovaLinkButton
                    color={"blueOutline"}
                    destination={`/book-a-meeting`}
                    disabled={false}
                    iconPosition={"none"}
                    slot={
                      <VectorSvgIcon
                        className={classNames(projectcss.all, sty.svg__cr1I)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wZvT
                      )}
                    >
                      {"See Pricing"}
                    </div>
                  </HypernovaLinkButton>
                </React.Fragment>
              ),
              value: args.children
            })}
          </div>
        ) : null}
        {(
          hasVariant($state, "socialProofDisabled", "socialProofDisabled")
            ? false
            : true
        ) ? (
          <div
            data-plasmic-name={"social"}
            data-plasmic-override={overrides.social}
            className={classNames(projectcss.all, sty.social, {
              [sty.socialsocialProofDisabled]: hasVariant(
                $state,
                "socialProofDisabled",
                "socialProofDisabled"
              )
            })}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__pVeQz)}
              displayHeight={"34px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hypernova_inc/images/image43.svg",
                fullWidth: 58,
                fullHeight: 35,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__rlaIh)}
              displayHeight={"34px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hypernova_inc/images/image44.svg",
                fullWidth: 105,
                fullHeight: 36,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__tB7Mg)}
              displayHeight={"34px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hypernova_inc/images/image45.svg",
                fullWidth: 152,
                fullHeight: 32,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__taAa8)}
              displayHeight={"34px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/hypernova_inc/images/image4.svg",
                fullWidth: 176,
                fullHeight: 39,
                aspectRatio: undefined
              }}
            />
          </div>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  sectionHero: ["sectionHero", "content", "social"],
  content: ["content", "social"],
  social: ["social"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  sectionHero: "div";
  content: "div";
  social: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHero__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHero__VariantsArgs;
    args?: PlasmicHero__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHero__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHero__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHero__ArgProps,
          internalVariantPropNames: PlasmicHero__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHero__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "sectionHero") {
    func.displayName = "PlasmicHero";
  } else {
    func.displayName = `PlasmicHero.${nodeName}`;
  }
  return func;
}

export const PlasmicHero = Object.assign(
  // Top-level PlasmicHero renders the root element
  makeNodeComponent("sectionHero"),
  {
    // Helper components rendering sub-elements
    content: makeNodeComponent("content"),
    social: makeNodeComponent("social"),

    // Metadata about props expected for PlasmicHero
    internalVariantProps: PlasmicHero__VariantProps,
    internalArgProps: PlasmicHero__ArgProps
  }
);

export default PlasmicHero;
/* prettier-ignore-end */
