/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: ydgBLCRsK_6P

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import GlobalShell from "../../GlobalShell"; // plasmic-import: VYweC3w_Jh99/component
import Section from "../../Section"; // plasmic-import: FaKfIdG9aMZc/component
import Hero from "../../Hero"; // plasmic-import: 6HGOGZ6Em2sv/component
import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import { ParallaxWrapper } from "@plasmicpkgs/react-scroll-parallax";
import GradientAtmosphere from "../../GradientAtmosphere"; // plasmic-import: QTTe92wC06bw/component
import BlurbCard from "../../BlurbCard"; // plasmic-import: AS_J8BsUuYTm/component
import ProductionStepsCard from "../../ProductionStepsCard"; // plasmic-import: 7SYzGLcFshQm/component
import TechnologyList from "../../TechnologyList"; // plasmic-import: qMedUY4rzZf9/component
import WhyWereDifferentCard from "../../WhyWereDifferentCard"; // plasmic-import: 5DPwz6sQoma2/component
import Footer from "../../Footer"; // plasmic-import: XJ7-8nUHEe46/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicConvertVibeCodeToProductionQuality.module.css"; // plasmic-import: ydgBLCRsK_6P/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: k4QR0HpbesmK/icon
import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: UosIBoZBJdWT/icon
import Icon71Icon from "./icons/PlasmicIcon__Icon71"; // plasmic-import: 3HJ2LylcNLxX/icon
import Icon72Icon from "./icons/PlasmicIcon__Icon72"; // plasmic-import: ZFs9QHeqjs9o/icon
import Icon73Icon from "./icons/PlasmicIcon__Icon73"; // plasmic-import: IbV6XjeF7v4q/icon
import Icon74Icon from "./icons/PlasmicIcon__Icon74"; // plasmic-import: JMSZX20zR7i5/icon
import Icon76Icon from "./icons/PlasmicIcon__Icon76"; // plasmic-import: w5DPorfxmZZf/icon
import Icon75Icon from "./icons/PlasmicIcon__Icon75"; // plasmic-import: 1QxHE4vDx658/icon
import Icon77Icon from "./icons/PlasmicIcon__Icon77"; // plasmic-import: dlCzBjKs2XHq/icon
import Icon79Icon from "./icons/PlasmicIcon__Icon79"; // plasmic-import: XObYFoACuXwf/icon
import Icon31Icon from "./icons/PlasmicIcon__Icon31"; // plasmic-import: WTHf47GHZTrx/icon

createPlasmicElementProxy;

export type PlasmicConvertVibeCodeToProductionQuality__VariantMembers = {};
export type PlasmicConvertVibeCodeToProductionQuality__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicConvertVibeCodeToProductionQuality__VariantsArgs;
export const PlasmicConvertVibeCodeToProductionQuality__VariantProps =
  new Array<VariantPropType>();

export type PlasmicConvertVibeCodeToProductionQuality__ArgsType = {};
type ArgPropType = keyof PlasmicConvertVibeCodeToProductionQuality__ArgsType;
export const PlasmicConvertVibeCodeToProductionQuality__ArgProps =
  new Array<ArgPropType>();

export type PlasmicConvertVibeCodeToProductionQuality__OverridesType = {
  root?: Flex__<"div">;
  globalShell?: Flex__<typeof GlobalShell>;
  hero?: Flex__<typeof Section>;
  h1?: Flex__<"h1">;
  gradientAtmosphere?: Flex__<typeof GradientAtmosphere>;
  whyVibecodedBreaks?: Flex__<typeof Section>;
  blurbCard?: Flex__<typeof BlurbCard>;
  howWeDoIt?: Flex__<typeof Section>;
  techStack?: Flex__<typeof Section>;
  technologyList?: Flex__<typeof TechnologyList>;
  whyDifferent?: Flex__<typeof Section>;
  span?: Flex__<"span">;
};

export interface DefaultConvertVibeCodeToProductionQualityProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicConvertVibeCodeToProductionQuality__RenderFunc(props: {
  variants: PlasmicConvertVibeCodeToProductionQuality__VariantsArgs;
  args: PlasmicConvertVibeCodeToProductionQuality__ArgsType;
  overrides: PlasmicConvertVibeCodeToProductionQuality__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">
          {PlasmicConvertVibeCodeToProductionQuality.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicConvertVibeCodeToProductionQuality.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicConvertVibeCodeToProductionQuality.pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={
            PlasmicConvertVibeCodeToProductionQuality.pageMetadata.description
          }
        />
        <meta
          key="og:description"
          property="og:description"
          content={
            PlasmicConvertVibeCodeToProductionQuality.pageMetadata.description
          }
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={
            PlasmicConvertVibeCodeToProductionQuality.pageMetadata.description
          }
        />
        <meta
          key="og:image"
          property="og:image"
          content={
            PlasmicConvertVibeCodeToProductionQuality.pageMetadata.ogImageSrc
          }
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={
            PlasmicConvertVibeCodeToProductionQuality.pageMetadata.ogImageSrc
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <GlobalShell
            data-plasmic-name={"globalShell"}
            data-plasmic-override={overrides.globalShell}
            className={classNames("__wab_instance", sty.globalShell)}
            main={
              <div className={classNames(projectcss.all, sty.freeBox__dhHl4)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___3JRD)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "auto"
                      : "auto"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "auto"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/hypernova_inc/images/atmosphereBackgroundPng4.png",
                    fullWidth: 937,
                    fullHeight: 605,
                    aspectRatio: undefined
                  }}
                />

                <Section
                  data-plasmic-name={"hero"}
                  data-plasmic-override={overrides.hero}
                  bgImage={
                    <React.Fragment>
                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.scrollParallax___33Qv1
                        )}
                        speed={20}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__xPtQk)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "tablet")
                              ? "60vw"
                              : "20vw"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/hypernova_inc/images/astronautFloatingPng2.png",
                            fullWidth: 2796,
                            fullHeight: 2648,
                            aspectRatio: undefined
                          }}
                        />
                      </ParallaxWrapper>
                      <GradientAtmosphere
                        data-plasmic-name={"gradientAtmosphere"}
                        data-plasmic-override={overrides.gradientAtmosphere}
                        className={classNames(
                          "__wab_instance",
                          sty.gradientAtmosphere
                        )}
                      />

                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.scrollParallax__bjSe0
                        )}
                        speed={20}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__uFtZf)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20vw"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/hypernova_inc/images/adobeStock802381366Png.png",
                            fullWidth: 4608,
                            fullHeight: 3072,
                            aspectRatio: undefined
                          }}
                        />
                      </ParallaxWrapper>
                    </React.Fragment>
                  }
                  className={classNames("__wab_instance", sty.hero)}
                  sectionContent={
                    <Hero
                      className={classNames("__wab_instance", sty.hero__uzvhH)}
                      description={
                        "AI can spark an idea. But only senior engineers can turn that idea into a production quality product."
                      }
                      heading={
                        <h1
                          data-plasmic-name={"h1"}
                          data-plasmic-override={overrides.h1}
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"When "}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-CtevabluNWTZ)" }}
                            >
                              {"Vibe Coded Apps"}
                            </span>
                            <React.Fragment>
                              {
                                " Hit Their Limit, We Take You the Rest of the Way"
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </h1>
                      }
                      socialProofDisabled={true}
                      subheadingDisabled={true}
                    >
                      <HypernovaLinkButton
                        destination={`/book-a-meeting`}
                        disabled={false}
                        iconPosition={"right"}
                        slot={
                          <IconIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__n3N2W
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___23J7
                          )}
                        >
                          {"Get Started"}
                        </div>
                      </HypernovaLinkButton>
                      <HypernovaLinkButton
                        color={"blueOutline"}
                        destination={`/tools/ai-project-estimator#${"project-estimator"}`}
                        disabled={false}
                        iconPosition={"none"}
                        slot={
                          <VectorSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__gae7F
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rStbh
                          )}
                        >
                          {"Get an Instant Estimate"}
                        </div>
                      </HypernovaLinkButton>
                    </Hero>
                  }
                />

                <Section
                  data-plasmic-name={"whyVibecodedBreaks"}
                  data-plasmic-override={overrides.whyVibecodedBreaks}
                  bgImage={
                    <ParallaxWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.scrollParallax__gM6H9
                      )}
                      speed={20}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__efq3J)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "75vw"
                            : "30vw"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/hypernova_inc/images/adobeStock946221956Png.png",
                          fullWidth: 3400,
                          fullHeight: 3400,
                          aspectRatio: undefined
                        }}
                      />
                    </ParallaxWrapper>
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.whyVibecodedBreaks
                  )}
                  h2={null}
                  header={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? undefined
                      : undefined
                  }
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jPnE2)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          sty.h2__hMgsp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rSm5I
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {"Why Vibe Coded Apps "}
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-CtevabluNWTZ)" }}
                            >
                              {"Break Under Real Use Issues"}
                            </span>
                          </React.Fragment>
                        </div>
                      </h2>
                      <BlurbCard
                        data-plasmic-name={"blurbCard"}
                        data-plasmic-override={overrides.blurbCard}
                        className={classNames("__wab_instance", sty.blurbCard)}
                        primary={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__eO7N
                            )}
                          >
                            {
                              "Large language models often generate functions, classes, or library names that don\u2019t actually exist. Even top models continue to hallucinate under uncertainty."
                            }
                          </div>
                        }
                        title={"Hallucinated or Confabulated Code"}
                      />
                    </div>
                  }
                />

                <Section
                  data-plasmic-name={"howWeDoIt"}
                  data-plasmic-override={overrides.howWeDoIt}
                  backgroundDisabled={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : undefined
                  }
                  bgImage={
                    <ParallaxWrapper
                      className={classNames(
                        "__wab_instance",
                        sty.scrollParallax__pdYiY
                      )}
                      speed={20}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__lm3GA)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/hypernova_inc/images/group1371CopyPng.png",
                          fullWidth: 1920,
                          fullHeight: 1705,
                          aspectRatio: undefined
                        }}
                      />
                    </ParallaxWrapper>
                  }
                  className={classNames("__wab_instance", sty.howWeDoIt)}
                  h2={
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__jupol
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"How to Convert Vibe Code to "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-CtevabluNWTZ)" }}
                        >
                          {"Production"}
                        </span>
                      </React.Fragment>
                    </h2>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__d7Bvx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__n43Jj
                        )}
                      >
                        <ProductionStepsCard
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dUliv
                              )}
                            >
                              {
                                "We review your existing code, architecture, dependencies, and security posture."
                              }
                            </div>
                          }
                          icon={
                            <Icon71Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__zUJjB
                              )}
                              role={"img"}
                            />
                          }
                          title={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zGlQn
                              )}
                            >
                              {"Audit & Assessment"}
                            </div>
                          }
                        />

                        <ProductionStepsCard
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__t55Kj
                              )}
                            >
                              {
                                "Move secrets to vaults, patch vulnerabilities, enforce authentication and authorization."
                              }
                            </div>
                          }
                          icon={
                            <Icon72Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___520Pi
                              )}
                              role={"img"}
                            />
                          }
                          title={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___7UUFo
                              )}
                            >
                              {"Stabilize & Secure"}
                            </div>
                          }
                        />

                        <ProductionStepsCard
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___8Fshj
                              )}
                            >
                              {
                                " Introduce modular structure, \nCI/CD, infrastructure patterns, observability"
                              }
                            </div>
                          }
                          icon={
                            <Icon73Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__aZgMq
                              )}
                              role={"img"}
                            />
                          }
                          title={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__cEbyt
                              )}
                            >
                              {"Re-Architect for Scale"}
                            </div>
                          }
                        />

                        <ProductionStepsCard
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ohuAi
                              )}
                            >
                              {
                                "Add test coverage, QA cycles, regression tests, performance validation."
                              }
                            </div>
                          }
                          icon={
                            <Icon74Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__thHge
                              )}
                              role={"img"}
                            />
                          }
                          title={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__bIlu
                              )}
                            >
                              {"Test & Validate"}
                            </div>
                          }
                        />

                        <ProductionStepsCard
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__l9Wu7
                              )}
                            >
                              {
                                "Use AI tools for speed, under \nsenior developer oversight and validation.\n"
                              }
                            </div>
                          }
                          icon={
                            <Icon76Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__cgmtv
                              )}
                              role={"img"}
                            />
                          }
                          title={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ewHi
                              )}
                            >
                              {"Enhance with AI (Safely) & Secure"}
                            </div>
                          }
                        />

                        <ProductionStepsCard
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tBfDe
                              )}
                            >
                              {
                                "Launch with monitoring, maintenance, rollback strategies, and ongoing iteration."
                              }
                            </div>
                          }
                          icon={
                            <Icon75Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__v0T1A
                              )}
                              role={"img"}
                            />
                          }
                          title={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___9QERe
                              )}
                            >
                              {"Deploy & Support"}
                            </div>
                          }
                        />
                      </div>
                    </div>
                  }
                />

                <Section
                  data-plasmic-name={"techStack"}
                  data-plasmic-override={overrides.techStack}
                  backgroundDisabled={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  }
                  bgImage={null}
                  className={classNames("__wab_instance", sty.techStack)}
                  h2={
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__kZOc
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"Built with Tools You "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-CtevabluNWTZ)" }}
                        >
                          {"Trust "}
                        </span>
                      </React.Fragment>
                    </h2>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7BMRu
                      )}
                    >
                      <TechnologyList
                        data-plasmic-name={"technologyList"}
                        data-plasmic-override={overrides.technologyList}
                        className={classNames(
                          "__wab_instance",
                          sty.technologyList
                        )}
                      />
                    </div>
                  }
                />

                <Section
                  data-plasmic-name={"whyDifferent"}
                  data-plasmic-override={overrides.whyDifferent}
                  backgroundDisabled={true}
                  bgImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___3E3Or)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"60%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hypernova_inc/images/frame2681Png.png",
                        fullWidth: 1920,
                        fullHeight: 892,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  className={classNames("__wab_instance", sty.whyDifferent)}
                  contentWidth={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "full"
                      : undefined
                  }
                  h2={
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__jSdRc
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"Convert Your Vibe Code with "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-CtevabluNWTZ)" }}
                        >
                          {"hypernova"}
                        </span>
                      </React.Fragment>
                    </h2>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vDf8B)}
                    >
                      <WhyWereDifferentCard
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sOOu
                            )}
                          >
                            {
                              "Our developers are here in the United States. With shared values, and clear communication, we're more productive. Period."
                            }
                          </div>
                        }
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__eAz2W
                            )}
                          >
                            {"U.S.A. Based Teams"}
                          </h3>
                        }
                      >
                        <Icon77Icon
                          className={classNames(projectcss.all, sty.svg__z24Ub)}
                          role={"img"}
                        />
                      </WhyWereDifferentCard>
                      <WhyWereDifferentCard
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__o5GDr
                            )}
                          >
                            {
                              "We've invested in meaningful collaboration and teamwork. We divide bigger, more complex tasks, fast."
                            }
                          </div>
                        }
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__prvQc
                            )}
                          >
                            {"Experienced Teams"}
                          </h3>
                        }
                      >
                        <Icon79Icon
                          className={classNames(projectcss.all, sty.svg__cooCm)}
                          role={"img"}
                        />
                      </WhyWereDifferentCard>
                      <WhyWereDifferentCard
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wJlJh
                            )}
                          >
                            {
                              "We use AI, automation, and machine learning where it counts. Your budget and timeline will thank you."
                            }
                          </div>
                        }
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__xSxIx
                            )}
                          >
                            {"AI Augmented Workflows"}
                          </h3>
                        }
                      >
                        <Icon31Icon
                          className={classNames(projectcss.all, sty.svg__dbk6F)}
                          role={"img"}
                        />
                      </WhyWereDifferentCard>
                    </div>
                  }
                  subheaderEnabled={true}
                  subheading={
                    <span
                      data-plasmic-name={"span"}
                      data-plasmic-override={overrides.span}
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.__wab_text,
                        sty.span
                      )}
                    >
                      {
                        "We combine human expertise with AI-driven efficiency to build enterprise-grade software that scales\u2014without the overhead of an in-house team."
                      }
                    </span>
                  }
                />
              </div>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "globalShell",
    "hero",
    "h1",
    "gradientAtmosphere",
    "whyVibecodedBreaks",
    "blurbCard",
    "howWeDoIt",
    "techStack",
    "technologyList",
    "whyDifferent",
    "span"
  ],
  globalShell: [
    "globalShell",
    "hero",
    "h1",
    "gradientAtmosphere",
    "whyVibecodedBreaks",
    "blurbCard",
    "howWeDoIt",
    "techStack",
    "technologyList",
    "whyDifferent",
    "span"
  ],
  hero: ["hero", "h1", "gradientAtmosphere"],
  h1: ["h1"],
  gradientAtmosphere: ["gradientAtmosphere"],
  whyVibecodedBreaks: ["whyVibecodedBreaks", "blurbCard"],
  blurbCard: ["blurbCard"],
  howWeDoIt: ["howWeDoIt"],
  techStack: ["techStack", "technologyList"],
  technologyList: ["technologyList"],
  whyDifferent: ["whyDifferent", "span"],
  span: ["span"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  globalShell: typeof GlobalShell;
  hero: typeof Section;
  h1: "h1";
  gradientAtmosphere: typeof GradientAtmosphere;
  whyVibecodedBreaks: typeof Section;
  blurbCard: typeof BlurbCard;
  howWeDoIt: typeof Section;
  techStack: typeof Section;
  technologyList: typeof TechnologyList;
  whyDifferent: typeof Section;
  span: "span";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicConvertVibeCodeToProductionQuality__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicConvertVibeCodeToProductionQuality__VariantsArgs;
    args?: PlasmicConvertVibeCodeToProductionQuality__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<
      PlasmicConvertVibeCodeToProductionQuality__VariantsArgs,
      ReservedPropsType
    > &
    // Specify args directly as props
    Omit<
      PlasmicConvertVibeCodeToProductionQuality__ArgsType,
      ReservedPropsType
    > &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicConvertVibeCodeToProductionQuality__ArgProps,
          internalVariantPropNames:
            PlasmicConvertVibeCodeToProductionQuality__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicConvertVibeCodeToProductionQuality__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicConvertVibeCodeToProductionQuality";
  } else {
    func.displayName = `PlasmicConvertVibeCodeToProductionQuality.${nodeName}`;
  }
  return func;
}

export const PlasmicConvertVibeCodeToProductionQuality = Object.assign(
  // Top-level PlasmicConvertVibeCodeToProductionQuality renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    globalShell: makeNodeComponent("globalShell"),
    hero: makeNodeComponent("hero"),
    h1: makeNodeComponent("h1"),
    gradientAtmosphere: makeNodeComponent("gradientAtmosphere"),
    whyVibecodedBreaks: makeNodeComponent("whyVibecodedBreaks"),
    blurbCard: makeNodeComponent("blurbCard"),
    howWeDoIt: makeNodeComponent("howWeDoIt"),
    techStack: makeNodeComponent("techStack"),
    technologyList: makeNodeComponent("technologyList"),
    whyDifferent: makeNodeComponent("whyDifferent"),
    span: makeNodeComponent("span"),

    // Metadata about props expected for PlasmicConvertVibeCodeToProductionQuality
    internalVariantProps:
      PlasmicConvertVibeCodeToProductionQuality__VariantProps,
    internalArgProps: PlasmicConvertVibeCodeToProductionQuality__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "hypernova | Convert Vibe Code to Production Quality",
      description:
        "Turn your AI-generated prototype into a production-quality application. hypernova’s U.S. based developers transform vibe-coded projects into secure, scalable, and high-performance software built to last. How to turn your vibe code into production quality!",
      ogImageSrc:
        "https://site-assets.plasmic.app/c2a13eff0aa5b9cfade8fc1d70b1ccd6.png",
      canonical: ""
    }
  }
);

export default PlasmicConvertVibeCodeToProductionQuality;
/* prettier-ignore-end */
