/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: Ii7KdNgpc_YO

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HamburgerMenu from "../../HamburgerMenu"; // plasmic-import: h_0WGuOlRb9O/component
import { SideEffect } from "@plasmicpkgs/plasmic-basic-components";
import NavigationLink from "../../NavigationLink"; // plasmic-import: dXmoAp3AxW__/component
import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicNavigationBar.module.css"; // plasmic-import: Ii7KdNgpc_YO/css

import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: UosIBoZBJdWT/icon
import Icon46Icon from "./icons/PlasmicIcon__Icon46"; // plasmic-import: 5nfb_9p9ple9/icon

createPlasmicElementProxy;

export type PlasmicNavigationBar__VariantMembers = {
  isOpen: "isOpen";
  backgroundColor: "clear" | "black" | "blur10";
};
export type PlasmicNavigationBar__VariantsArgs = {
  isOpen?: SingleBooleanChoiceArg<"isOpen">;
  backgroundColor?: SingleChoiceArg<"clear" | "black" | "blur10">;
};
type VariantPropType = keyof PlasmicNavigationBar__VariantsArgs;
export const PlasmicNavigationBar__VariantProps = new Array<VariantPropType>(
  "isOpen",
  "backgroundColor"
);

export type PlasmicNavigationBar__ArgsType = { children?: React.ReactNode };
type ArgPropType = keyof PlasmicNavigationBar__ArgsType;
export const PlasmicNavigationBar__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicNavigationBar__OverridesType = {
  root?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  hamburgerMenu?: Flex__<typeof HamburgerMenu>;
  sideEffect?: Flex__<typeof SideEffect>;
  services?: Flex__<typeof NavigationLink>;
  technologies?: Flex__<typeof NavigationLink>;
  insights?: Flex__<typeof NavigationLink>;
  navigationLink?: Flex__<typeof NavigationLink>;
  contactUs?: Flex__<typeof HypernovaLinkButton>;
  _888Hyprnva?: Flex__<typeof HypernovaLinkButton>;
  getAnInstantEstimateButton?: Flex__<typeof HypernovaLinkButton>;
};

export interface DefaultNavigationBarProps {
  children?: React.ReactNode;
  isOpen?: SingleBooleanChoiceArg<"isOpen">;
  backgroundColor?: SingleChoiceArg<"clear" | "black" | "blur10">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavigationBar__RenderFunc(props: {
  variants: PlasmicNavigationBar__VariantsArgs;
  args: PlasmicNavigationBar__ArgsType;
  overrides: PlasmicNavigationBar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isOpen",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isOpen
      },
      {
        path: "backgroundColor",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.backgroundColor
      },
      {
        path: "isOpen2",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => true
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootbackgroundColor_black]: hasVariant(
            $state,
            "backgroundColor",
            "black"
          ),
          [sty.rootbackgroundColor_blur10]: hasVariant(
            $state,
            "backgroundColor",
            "blur10"
          ),
          [sty.rootbackgroundColor_blur10_isOpen]:
            hasVariant($state, "isOpen", "isOpen") &&
            hasVariant($state, "backgroundColor", "blur10"),
          [sty.rootbackgroundColor_clear]: hasVariant(
            $state,
            "backgroundColor",
            "clear"
          ),
          [sty.rootisOpen]: hasVariant($state, "isOpen", "isOpen")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__w03Dl, {
          [sty.freeBoxbackgroundColor_black__w03DlU40M]: hasVariant(
            $state,
            "backgroundColor",
            "black"
          ),
          [sty.freeBoxbackgroundColor_blur10__w03DlLhjnl]: hasVariant(
            $state,
            "backgroundColor",
            "blur10"
          ),
          [sty.freeBoxbackgroundColor_blur10_isOpen__w03DlLhjnlN6Win]:
            hasVariant($state, "isOpen", "isOpen") &&
            hasVariant($state, "backgroundColor", "blur10"),
          [sty.freeBoxisOpen__w03Dln6Win]: hasVariant(
            $state,
            "isOpen",
            "isOpen"
          )
        })}
      >
        <PlasmicLink__
          data-plasmic-name={"link"}
          data-plasmic-override={overrides.link}
          className={classNames(projectcss.all, projectcss.a, sty.link, {
            [sty.linkisOpen]: hasVariant($state, "isOpen", "isOpen")
          })}
          component={Link}
          href={`/`}
          platform={"nextjs"}
        >
          {renderPlasmicSlot({
            defaultContents: null,
            value: args.children
          })}
        </PlasmicLink__>
        {(
          hasVariant(globalVariants, "screen", "mobileOnly")
            ? true
            : hasVariant(globalVariants, "screen", "tablet")
              ? true
              : false
        ) ? (
          <HamburgerMenu
            data-plasmic-name={"hamburgerMenu"}
            data-plasmic-override={overrides.hamburgerMenu}
            className={classNames("__wab_instance", sty.hamburgerMenu, {
              [sty.hamburgerMenuisOpen]: hasVariant($state, "isOpen", "isOpen")
            })}
            isOpen={
              hasVariant($state, "isOpen", "isOpen") &&
              hasVariant(globalVariants, "screen", "tablet")
                ? (() => {
                    try {
                      return (() => {
                        $state.isOpen2;
                        return true;
                      })();
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                : (() => {
                    try {
                      return (() => {
                        $state.isOpen2;
                        return false;
                      })();
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
            }
            onClick={async event => {
              const $steps = {};

              $steps["updateIsOpen2"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["isOpen2"]
                      },
                      operation: 4
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      const oldValue = $stateGet(objRoot, variablePath);
                      $stateSet(objRoot, variablePath, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsOpen2"] != null &&
                typeof $steps["updateIsOpen2"] === "object" &&
                typeof $steps["updateIsOpen2"].then === "function"
              ) {
                $steps["updateIsOpen2"] = await $steps["updateIsOpen2"];
              }

              $steps["updateIsOpen22"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "isOpen",
                      operation: 2,
                      value: "isOpen"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      const oldValue = $stateGet($state, vgroup);
                      $stateSet($state, vgroup, !oldValue);
                      return !oldValue;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsOpen22"] != null &&
                typeof $steps["updateIsOpen22"] === "object" &&
                typeof $steps["updateIsOpen22"].then === "function"
              ) {
                $steps["updateIsOpen22"] = await $steps["updateIsOpen22"];
              }
            }}
          />
        ) : null}
      </div>
      {(hasVariant(globalVariants, "screen", "mobileOnly") ? false : true) ? (
        <SideEffect
          data-plasmic-name={"sideEffect"}
          data-plasmic-override={overrides.sideEffect}
          className={classNames("__wab_instance", sty.sideEffect, {
            [sty.sideEffectisOpen]: hasVariant($state, "isOpen", "isOpen")
          })}
          onMount={async () => {
            const $steps = {};

            $steps["updateIsOpen"] = true
              ? (() => {
                  const actionArgs = {
                    vgroup: "isOpen",
                    operation: 6,
                    value: "isOpen"
                  };
                  return (({ vgroup, value }) => {
                    if (typeof value === "string") {
                      value = [value];
                    }

                    $stateSet($state, vgroup, false);
                    return false;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateIsOpen"] != null &&
              typeof $steps["updateIsOpen"] === "object" &&
              typeof $steps["updateIsOpen"].then === "function"
            ) {
              $steps["updateIsOpen"] = await $steps["updateIsOpen"];
            }
          }}
        />
      ) : null}
      {(
        hasVariant($state, "isOpen", "isOpen") &&
        hasVariant(globalVariants, "screen", "mobileOnly")
          ? true
          : hasVariant($state, "isOpen", "isOpen") &&
              hasVariant(globalVariants, "screen", "tablet")
            ? true
            : hasVariant(globalVariants, "screen", "mobileOnly")
              ? false
              : hasVariant(globalVariants, "screen", "tablet")
                ? true
                : true
      ) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__lJtw8, {
            [sty.freeBoxbackgroundColor_black__lJtw8U40M]: hasVariant(
              $state,
              "backgroundColor",
              "black"
            ),
            [sty.freeBoxbackgroundColor_blur10__lJtw8Lhjnl]: hasVariant(
              $state,
              "backgroundColor",
              "blur10"
            ),
            [sty.freeBoxbackgroundColor_blur10_isOpen__lJtw8LhjnlN6Win]:
              hasVariant($state, "isOpen", "isOpen") &&
              hasVariant($state, "backgroundColor", "blur10"),
            [sty.freeBoxisOpen__lJtw8N6Win]: hasVariant(
              $state,
              "isOpen",
              "isOpen"
            )
          })}
        >
          <NavigationLink
            data-plasmic-name={"services"}
            data-plasmic-override={overrides.services}
            className={classNames("__wab_instance", sty.services, {
              [sty.servicesbackgroundColor_black]: hasVariant(
                $state,
                "backgroundColor",
                "black"
              ),
              [sty.servicesbackgroundColor_clear]: hasVariant(
                $state,
                "backgroundColor",
                "clear"
              ),
              [sty.servicesisOpen]: hasVariant($state, "isOpen", "isOpen")
            })}
            content={"Services"}
            destination={"/services"}
            onClick={async event => {
              const $steps = {};

              $steps["updateIsOpen"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "isOpen",
                      operation: 6,
                      value: "isOpen"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      $stateSet($state, vgroup, false);
                      return false;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsOpen"] != null &&
                typeof $steps["updateIsOpen"] === "object" &&
                typeof $steps["updateIsOpen"].then === "function"
              ) {
                $steps["updateIsOpen"] = await $steps["updateIsOpen"];
              }
            }}
            type={"line"}
          />

          <NavigationLink
            data-plasmic-name={"technologies"}
            data-plasmic-override={overrides.technologies}
            className={classNames("__wab_instance", sty.technologies, {
              [sty.technologiesisOpen]: hasVariant($state, "isOpen", "isOpen")
            })}
            content={"Technologies"}
            destination={`/technologies`}
            onClick={async event => {
              const $steps = {};

              $steps["updateIsOpen"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "isOpen",
                      operation: 6,
                      value: "isOpen"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      $stateSet($state, vgroup, false);
                      return false;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsOpen"] != null &&
                typeof $steps["updateIsOpen"] === "object" &&
                typeof $steps["updateIsOpen"].then === "function"
              ) {
                $steps["updateIsOpen"] = await $steps["updateIsOpen"];
              }
            }}
            type={"line"}
          />

          <NavigationLink
            data-plasmic-name={"insights"}
            data-plasmic-override={overrides.insights}
            className={classNames("__wab_instance", sty.insights, {
              [sty.insightsisOpen]: hasVariant($state, "isOpen", "isOpen")
            })}
            content={"Insights"}
            destination={`/insights`}
            onClick={async event => {
              const $steps = {};

              $steps["updateIsOpen"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: "isOpen",
                      operation: 6,
                      value: "isOpen"
                    };
                    return (({ vgroup, value }) => {
                      if (typeof value === "string") {
                        value = [value];
                      }

                      $stateSet($state, vgroup, false);
                      return false;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateIsOpen"] != null &&
                typeof $steps["updateIsOpen"] === "object" &&
                typeof $steps["updateIsOpen"].then === "function"
              ) {
                $steps["updateIsOpen"] = await $steps["updateIsOpen"];
              }
            }}
            type={"line"}
          />

          <NavigationLink
            data-plasmic-name={"navigationLink"}
            data-plasmic-override={overrides.navigationLink}
            className={classNames("__wab_instance", sty.navigationLink, {
              [sty.navigationLinkbackgroundColor_black]: hasVariant(
                $state,
                "backgroundColor",
                "black"
              ),
              [sty.navigationLinkbackgroundColor_clear]: hasVariant(
                $state,
                "backgroundColor",
                "clear"
              ),
              [sty.navigationLinkisOpen]: hasVariant($state, "isOpen", "isOpen")
            })}
            content={"Convert Vibe Code"}
            destination={`/solutions/convert-vibe-code-to-production-quality`}
            type={"line"}
          />

          <div
            className={classNames(projectcss.all, sty.freeBox___1TeMs, {
              [sty.freeBoxisOpen___1TeMsn6Win]: hasVariant(
                $state,
                "isOpen",
                "isOpen"
              )
            })}
          >
            {(
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? false
                : hasVariant(globalVariants, "screen", "tablet")
                  ? true
                  : false
            ) ? (
              <HypernovaLinkButton
                data-plasmic-name={"contactUs"}
                data-plasmic-override={overrides.contactUs}
                className={classNames("__wab_instance")}
                color={
                  hasVariant($state, "isOpen", "isOpen") &&
                  hasVariant(globalVariants, "screen", "tablet")
                    ? "blueOutline"
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? undefined
                      : "blueOutline"
                }
                destination={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? `/book-a-meeting`
                    : `/tools/ai-project-estimator#${"project-estimator"}`
                }
                disabled={false}
                iconPosition={
                  hasVariant($state, "isOpen", "isOpen") &&
                  hasVariant(globalVariants, "screen", "tablet")
                    ? "none"
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? "right"
                      : "none"
                }
                slot={
                  <PlasmicIcon__
                    PlasmicIconType={
                      hasVariant(globalVariants, "screen", "tablet")
                        ? Icon46Icon
                        : VectorSvgIcon
                    }
                    className={classNames(projectcss.all, sty.svg__rJzyO)}
                    role={"img"}
                  />
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jxZwh,
                    {
                      [sty.textisOpen__jxZwhn6Win]: hasVariant(
                        $state,
                        "isOpen",
                        "isOpen"
                      )
                    }
                  )}
                >
                  {hasVariant(globalVariants, "screen", "tablet")
                    ? "Book a Meeting with Us"
                    : "Get an Instant Estimate"}
                </div>
              </HypernovaLinkButton>
            ) : null}
            {(
              hasVariant($state, "isOpen", "isOpen") &&
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? true
                : false
            ) ? (
              <HypernovaLinkButton
                data-plasmic-name={"_888Hyprnva"}
                data-plasmic-override={overrides._888Hyprnva}
                borderRadius={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "_20Px"
                    : undefined
                }
                className={classNames("__wab_instance", sty._888Hyprnva, {
                  [sty._888HyprnvaisOpen]: hasVariant(
                    $state,
                    "isOpen",
                    "isOpen"
                  )
                })}
                color={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "blueOutline"
                    : undefined
                }
                destination={"tel: 888-497-7682"}
                iconPosition={"right"}
                padding={"_1330"}
                slot={
                  <Icon46Icon
                    className={classNames(projectcss.all, sty.svg__vumYs)}
                    role={"img"}
                  />
                }
              >
                <div className={classNames(projectcss.all, sty.freeBox__lmLja)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__n7Alq
                    )}
                  >
                    {"(888) HYPRNVA"}
                  </div>
                </div>
              </HypernovaLinkButton>
            ) : null}
          </div>
          <HypernovaLinkButton
            data-plasmic-name={"getAnInstantEstimateButton"}
            data-plasmic-override={overrides.getAnInstantEstimateButton}
            className={classNames(
              "__wab_instance",
              sty.getAnInstantEstimateButton,
              {
                [sty.getAnInstantEstimateButtonisOpen]: hasVariant(
                  $state,
                  "isOpen",
                  "isOpen"
                )
              }
            )}
            destination={
              hasVariant($state, "isOpen", "isOpen") &&
              hasVariant(globalVariants, "screen", "tablet")
                ? `/tools/ai-project-estimator#${"project-estimator"}`
                : hasVariant($state, "isOpen", "isOpen")
                  ? `/tools/ai-project-estimator`
                  : `/tools/ai-project-estimator#${"project-estimator"}`
            }
            disabled={false}
            iconPosition={"none"}
            slot={
              <VectorSvgIcon
                className={classNames(projectcss.all, sty.svg__stxSr)}
                role={"img"}
              />
            }
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__h58B1
              )}
            >
              {"Get an Instant Estimate"}
            </div>
          </HypernovaLinkButton>
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "link",
    "hamburgerMenu",
    "sideEffect",
    "services",
    "technologies",
    "insights",
    "navigationLink",
    "contactUs",
    "_888Hyprnva",
    "getAnInstantEstimateButton"
  ],
  link: ["link"],
  hamburgerMenu: ["hamburgerMenu"],
  sideEffect: ["sideEffect"],
  services: ["services"],
  technologies: ["technologies"],
  insights: ["insights"],
  navigationLink: ["navigationLink"],
  contactUs: ["contactUs"],
  _888Hyprnva: ["_888Hyprnva"],
  getAnInstantEstimateButton: ["getAnInstantEstimateButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
  hamburgerMenu: typeof HamburgerMenu;
  sideEffect: typeof SideEffect;
  services: typeof NavigationLink;
  technologies: typeof NavigationLink;
  insights: typeof NavigationLink;
  navigationLink: typeof NavigationLink;
  contactUs: typeof HypernovaLinkButton;
  _888Hyprnva: typeof HypernovaLinkButton;
  getAnInstantEstimateButton: typeof HypernovaLinkButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavigationBar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavigationBar__VariantsArgs;
    args?: PlasmicNavigationBar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavigationBar__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavigationBar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavigationBar__ArgProps,
          internalVariantPropNames: PlasmicNavigationBar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavigationBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavigationBar";
  } else {
    func.displayName = `PlasmicNavigationBar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavigationBar = Object.assign(
  // Top-level PlasmicNavigationBar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    hamburgerMenu: makeNodeComponent("hamburgerMenu"),
    sideEffect: makeNodeComponent("sideEffect"),
    services: makeNodeComponent("services"),
    technologies: makeNodeComponent("technologies"),
    insights: makeNodeComponent("insights"),
    navigationLink: makeNodeComponent("navigationLink"),
    contactUs: makeNodeComponent("contactUs"),
    _888Hyprnva: makeNodeComponent("_888Hyprnva"),
    getAnInstantEstimateButton: makeNodeComponent("getAnInstantEstimateButton"),

    // Metadata about props expected for PlasmicNavigationBar
    internalVariantProps: PlasmicNavigationBar__VariantProps,
    internalArgProps: PlasmicNavigationBar__ArgProps
  }
);

export default PlasmicNavigationBar;
/* prettier-ignore-end */
