/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: zokY4mlg8hP8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import GlobalShell from "../../GlobalShell"; // plasmic-import: VYweC3w_Jh99/component
import Section from "../../Section"; // plasmic-import: FaKfIdG9aMZc/component
import BlogPost from "../../BlogPost"; // plasmic-import: iSqAefpkD4Ss/component
import { CmsQueryRepeater } from "@plasmicpkgs/plasmic-cms";
import { PlasmicHead } from "@plasmicapp/react-web";
import { CmsRowField } from "@plasmicpkgs/plasmic-cms";
import { CmsRowImage } from "@plasmicpkgs/plasmic-cms";
import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import InsightStack from "../../InsightStack"; // plasmic-import: xV_gipCocVin/component
import Footer from "../../Footer"; // plasmic-import: XJ7-8nUHEe46/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicSingleInsight.module.css"; // plasmic-import: zokY4mlg8hP8/css

createPlasmicElementProxy;

export type PlasmicSingleInsight__VariantMembers = {};
export type PlasmicSingleInsight__VariantsArgs = {};
type VariantPropType = keyof PlasmicSingleInsight__VariantsArgs;
export const PlasmicSingleInsight__VariantProps = new Array<VariantPropType>();

export type PlasmicSingleInsight__ArgsType = {};
type ArgPropType = keyof PlasmicSingleInsight__ArgsType;
export const PlasmicSingleInsight__ArgProps = new Array<ArgPropType>();

export type PlasmicSingleInsight__OverridesType = {
  root?: Flex__<"div">;
  globalShell?: Flex__<typeof GlobalShell>;
  section?: Flex__<typeof Section>;
  blogPost?: Flex__<typeof BlogPost>;
  pageMetadataOverride?: Flex__<typeof PlasmicHead>;
  post?: Flex__<"div">;
  hypernovaLinkButton?: Flex__<typeof HypernovaLinkButton>;
  latestInsights?: Flex__<typeof Section>;
  insightStack?: Flex__<typeof InsightStack>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultSingleInsightProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSingleInsight__RenderFunc(props: {
  variants: PlasmicSingleInsight__VariantsArgs;
  args: PlasmicSingleInsight__ArgsType;
  overrides: PlasmicSingleInsight__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <GlobalShell
            data-plasmic-name={"globalShell"}
            data-plasmic-override={overrides.globalShell}
            className={classNames("__wab_instance", sty.globalShell)}
            footerWrapper={
              <React.Fragment>
                <Section
                  data-plasmic-name={"latestInsights"}
                  data-plasmic-override={overrides.latestInsights}
                  backgroundDisabled={true}
                  bgImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__x6Rrr)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hypernova_inc/images/vector1Png.png",
                        fullWidth: 1920,
                        fullHeight: 2481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  className={classNames("__wab_instance", sty.latestInsights)}
                  h2={"Latest Insights"}
                  header={true}
                  sectionContent={
                    <InsightStack
                      data-plasmic-name={"insightStack"}
                      data-plasmic-override={overrides.insightStack}
                      className={classNames("__wab_instance", sty.insightStack)}
                      limit={"_4"}
                    />
                  }
                  subheading={
                    "We combine human expertise with AI-driven efficiency to build enterprise-grade software that scales\u2014without the overhead of an in-house team."
                  }
                />

                <Footer
                  data-plasmic-name={"footer"}
                  data-plasmic-override={overrides.footer}
                  className={classNames("__wab_instance", sty.footer)}
                >
                  {"Don't fall into chaos..."}
                </Footer>
              </React.Fragment>
            }
            main={
              <div className={classNames(projectcss.all, sty.freeBox__saRzd)}>
                <Section
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  bgImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jMjaD)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={(() => {
                        try {
                          return undefined;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                    />
                  }
                  className={classNames("__wab_instance", sty.section)}
                  sectionContent={
                    <React.Fragment>
                      <BlogPost
                        data-plasmic-name={"blogPost"}
                        data-plasmic-override={overrides.blogPost}
                        className={classNames("__wab_instance", sty.blogPost)}
                      >
                        <CmsQueryRepeater
                          className={classNames(
                            "__wab_instance",
                            sty.cmsDataFetcher__sZau3
                          )}
                          desc={false}
                          emptyMessage={
                            <DataCtxReader__>
                              {$ctx => (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__o68Mp
                                  )}
                                >
                                  {"No matching published entries found."}
                                </div>
                              )}
                            </DataCtxReader__>
                          }
                          filterField={"_id"}
                          filterValue={(() => {
                            try {
                              return $ctx.params.slug;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          forceEmptyState={false}
                          forceLoadingState={false}
                          limit={0}
                          loadingMessage={
                            <DataCtxReader__>
                              {$ctx => (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__fSWn
                                  )}
                                >
                                  {"Loading..."}
                                </div>
                              )}
                            </DataCtxReader__>
                          }
                          noAutoRepeat={false}
                          noLayout={false}
                          table={"blogs"}
                          useDraft={false}
                        >
                          <DataCtxReader__>
                            {$ctx => (
                              <React.Fragment>
                                <PlasmicHead
                                  data-plasmic-name={"pageMetadataOverride"}
                                  data-plasmic-override={
                                    overrides.pageMetadataOverride
                                  }
                                  description={(() => {
                                    try {
                                      return $ctx.plasmicCmsBlogsItem.data
                                        .synopsis;
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return undefined;
                                      }
                                      throw e;
                                    }
                                  })()}
                                  image={(() => {
                                    try {
                                      return $ctx.plasmicCmsBlogsItem.data.image
                                        .url;
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return "/plasmic/hypernova_inc/images/insightsOgPng.png";
                                      }
                                      throw e;
                                    }
                                  })()}
                                  title={(() => {
                                    try {
                                      return $ctx.plasmicCmsBlogsItem.data
                                        .title;
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return undefined;
                                      }
                                      throw e;
                                    }
                                  })()}
                                />

                                <div
                                  data-plasmic-name={"post"}
                                  data-plasmic-override={overrides.post}
                                  className={classNames(
                                    projectcss.all,
                                    sty.post
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__hzrFe
                                    )}
                                  >
                                    <CmsRowField
                                      className={classNames(
                                        "__wab_instance",
                                        sty.cmsEntryField__qrIyg
                                      )}
                                      themeResetClassName={classNames(
                                        projectcss.root_reset,
                                        projectcss.root_reset_tags,
                                        projectcss.plasmic_default_styles,
                                        projectcss.plasmic_mixins,
                                        styleTokensClassNames
                                      )}
                                    />

                                    <CmsQueryRepeater
                                      className={classNames(
                                        "__wab_instance",
                                        sty.cmsDataFetcher__q1Lh
                                      )}
                                      desc={false}
                                      emptyMessage={
                                        <DataCtxReader__>
                                          {$ctx => (
                                            <div
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.text__q6Guy
                                              )}
                                            >
                                              {
                                                "No matching published entries found."
                                              }
                                            </div>
                                          )}
                                        </DataCtxReader__>
                                      }
                                      filterField={"_id"}
                                      filterValue={(() => {
                                        try {
                                          return $ctx.plasmicCmsBlogsItem.data
                                            .author;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return undefined;
                                          }
                                          throw e;
                                        }
                                      })()}
                                      forceEmptyState={false}
                                      forceLoadingState={false}
                                      limit={0}
                                      loadingMessage={
                                        <DataCtxReader__>
                                          {$ctx => (
                                            <div
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.text__ldTav
                                              )}
                                            >
                                              {"Loading..."}
                                            </div>
                                          )}
                                        </DataCtxReader__>
                                      }
                                      noAutoRepeat={false}
                                      noLayout={false}
                                      table={"partners"}
                                      useDraft={false}
                                    >
                                      <DataCtxReader__>
                                        {$ctx => (
                                          <div
                                            className={classNames(
                                              projectcss.all,
                                              sty.freeBox__wXAx
                                            )}
                                          >
                                            <div
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.text__w8Xwp
                                              )}
                                            >
                                              {"Article by:"}
                                            </div>
                                            <CmsRowImage
                                              className={classNames(
                                                "__wab_instance",
                                                sty.cmsEntryImage__fhhCx
                                              )}
                                              srcProp={"src"}
                                            >
                                              <PlasmicImg__
                                                alt={""}
                                                className={classNames(
                                                  sty.img__dlr5Y
                                                )}
                                                displayHeight={"40px"}
                                                displayMaxHeight={"none"}
                                                displayMaxWidth={"none"}
                                                displayMinHeight={"0"}
                                                displayMinWidth={"0"}
                                                displayWidth={"40px"}
                                                src={
                                                  "https://studio.plasmic.app/static/img/placeholder-full.png"
                                                }
                                              />
                                            </CmsRowImage>
                                            <CmsRowField
                                              className={classNames(
                                                "__wab_instance",
                                                sty.cmsEntryField__glqJz
                                              )}
                                              field={"name"}
                                              themeResetClassName={classNames(
                                                projectcss.root_reset,
                                                projectcss.root_reset_tags,
                                                projectcss.plasmic_default_styles,
                                                projectcss.plasmic_mixins,
                                                styleTokensClassNames
                                              )}
                                            />
                                          </div>
                                        )}
                                      </DataCtxReader__>
                                    </CmsQueryRepeater>
                                    <CmsRowImage
                                      className={classNames(
                                        "__wab_instance",
                                        sty.cmsEntryImage__rjsRo
                                      )}
                                      srcProp={"src"}
                                    >
                                      <PlasmicImg__
                                        alt={""}
                                        className={classNames(sty.img__k0Pgh)}
                                        displayHeight={"100%"}
                                        displayMaxHeight={"360px"}
                                        displayMaxWidth={"none"}
                                        displayMinHeight={"0"}
                                        displayMinWidth={"0"}
                                        displayWidth={"100%"}
                                        src={
                                          "https://studio.plasmic.app/static/img/placeholder-full.png"
                                        }
                                      />
                                    </CmsRowImage>
                                    <CmsRowField
                                      className={classNames(
                                        "__wab_instance",
                                        sty.cmsEntryField__eRpXj
                                      )}
                                      field={"synopsis"}
                                      themeResetClassName={classNames(
                                        projectcss.root_reset,
                                        projectcss.root_reset_tags,
                                        projectcss.plasmic_default_styles,
                                        projectcss.plasmic_mixins,
                                        styleTokensClassNames
                                      )}
                                    />

                                    <CmsRowField
                                      className={classNames(
                                        "__wab_instance",
                                        sty.cmsEntryField__caPlH
                                      )}
                                      field={"body"}
                                      themeResetClassName={classNames(
                                        projectcss.root_reset,
                                        projectcss.root_reset_tags,
                                        projectcss.plasmic_default_styles,
                                        projectcss.plasmic_mixins,
                                        styleTokensClassNames
                                      )}
                                      usePlasmicTheme={false}
                                    />
                                  </div>
                                </div>
                              </React.Fragment>
                            )}
                          </DataCtxReader__>
                        </CmsQueryRepeater>
                      </BlogPost>
                      <HypernovaLinkButton
                        data-plasmic-name={"hypernovaLinkButton"}
                        data-plasmic-override={overrides.hypernovaLinkButton}
                        className={classNames(
                          "__wab_instance",
                          sty.hypernovaLinkButton
                        )}
                        color={"blueOutline"}
                        destination={`/book-a-meeting`}
                        iconPosition={"none"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__riMw8
                          )}
                        >
                          {"Contact us for personalized insights"}
                        </div>
                      </HypernovaLinkButton>
                    </React.Fragment>
                  }
                />
              </div>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "globalShell",
    "section",
    "blogPost",
    "pageMetadataOverride",
    "post",
    "hypernovaLinkButton",
    "latestInsights",
    "insightStack",
    "footer"
  ],
  globalShell: [
    "globalShell",
    "section",
    "blogPost",
    "pageMetadataOverride",
    "post",
    "hypernovaLinkButton",
    "latestInsights",
    "insightStack",
    "footer"
  ],
  section: [
    "section",
    "blogPost",
    "pageMetadataOverride",
    "post",
    "hypernovaLinkButton"
  ],
  blogPost: ["blogPost", "pageMetadataOverride", "post"],
  pageMetadataOverride: ["pageMetadataOverride"],
  post: ["post"],
  hypernovaLinkButton: ["hypernovaLinkButton"],
  latestInsights: ["latestInsights", "insightStack"],
  insightStack: ["insightStack"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  globalShell: typeof GlobalShell;
  section: typeof Section;
  blogPost: typeof BlogPost;
  pageMetadataOverride: typeof PlasmicHead;
  post: "div";
  hypernovaLinkButton: typeof HypernovaLinkButton;
  latestInsights: typeof Section;
  insightStack: typeof InsightStack;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSingleInsight__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSingleInsight__VariantsArgs;
    args?: PlasmicSingleInsight__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSingleInsight__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSingleInsight__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSingleInsight__ArgProps,
          internalVariantPropNames: PlasmicSingleInsight__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSingleInsight__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSingleInsight";
  } else {
    func.displayName = `PlasmicSingleInsight.${nodeName}`;
  }
  return func;
}

export const PlasmicSingleInsight = Object.assign(
  // Top-level PlasmicSingleInsight renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    globalShell: makeNodeComponent("globalShell"),
    section: makeNodeComponent("section"),
    blogPost: makeNodeComponent("blogPost"),
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),
    post: makeNodeComponent("post"),
    hypernovaLinkButton: makeNodeComponent("hypernovaLinkButton"),
    latestInsights: makeNodeComponent("latestInsights"),
    insightStack: makeNodeComponent("insightStack"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicSingleInsight
    internalVariantProps: PlasmicSingleInsight__VariantProps,
    internalArgProps: PlasmicSingleInsight__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSingleInsight;
/* prettier-ignore-end */
