/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: Ing9D1G9uHeb

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CmsRowImage } from "@plasmicpkgs/plasmic-cms";
import { CmsRowField } from "@plasmicpkgs/plasmic-cms";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicTechTile.module.css"; // plasmic-import: Ing9D1G9uHeb/css

createPlasmicElementProxy;

export type PlasmicTechTile__VariantMembers = {
  size: "large" | "small";
  color: "blue";
  iconSize: "large";
};
export type PlasmicTechTile__VariantsArgs = {
  size?: SingleChoiceArg<"large" | "small">;
  color?: SingleChoiceArg<"blue">;
  iconSize?: SingleChoiceArg<"large">;
};
type VariantPropType = keyof PlasmicTechTile__VariantsArgs;
export const PlasmicTechTile__VariantProps = new Array<VariantPropType>(
  "size",
  "color",
  "iconSize"
);

export type PlasmicTechTile__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicTechTile__ArgsType;
export const PlasmicTechTile__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicTechTile__OverridesType = {
  root?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultTechTileProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  size?: SingleChoiceArg<"large" | "small">;
  color?: SingleChoiceArg<"blue">;
  iconSize?: SingleChoiceArg<"large">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTechTile__RenderFunc(props: {
  variants: PlasmicTechTile__VariantsArgs;
  args: PlasmicTechTile__ArgsType;
  overrides: PlasmicTechTile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "size",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.size
      },
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.color
      },
      {
        path: "iconSize",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.iconSize
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootcolor_blue]: hasVariant($state, "color", "blue"),
          [sty.rootsize_large]: hasVariant($state, "size", "large"),
          [sty.rootsize_small]: hasVariant($state, "size", "small")
        }
      )}
      component={Link}
      href={`/technology/${(() => {
        try {
          return $ctx.plasmicCmsTechnologiesItem.id;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          }
          throw e;
        }
      })()}`}
      platform={"nextjs"}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__sFom, {
          [sty.freeBoxiconSize_large__sFomIv3P]: hasVariant(
            $state,
            "iconSize",
            "large"
          ),
          [sty.freeBoxsize_large__sFomVbXnm]: hasVariant(
            $state,
            "size",
            "large"
          ),
          [sty.freeBoxsize_small__sFomwmGef]: hasVariant(
            $state,
            "size",
            "small"
          )
        })}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <CmsRowImage
              className={classNames("__wab_instance", sty.cmsEntryImage__zaeWf)}
              srcProp={"src"}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox__sPHjU, {
                  [sty.freeBoxsize_small__sPHjUwmGef]: hasVariant(
                    $state,
                    "size",
                    "small"
                  )
                })}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__hYkLn)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  height={"34px"}
                  src={
                    "https://studio.plasmic.app/static/img/placeholder-full.png"
                  }
                  width={"34px"}
                />
              </div>
            </CmsRowImage>
          ),
          value: args.children
        })}
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__bgz22, {
          [sty.freeBoxsize_small__bgz22WmGef]: hasVariant(
            $state,
            "size",
            "small"
          )
        })}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <CmsRowField
              className={classNames(
                "__wab_instance",
                sty.cmsEntryField___9Trnh
              )}
              themeResetClassName={classNames(
                projectcss.root_reset,
                projectcss.root_reset_tags,
                projectcss.plasmic_default_styles,
                projectcss.plasmic_mixins,
                styleTokensClassNames
              )}
            />
          ),

          value: args.slot
        })}
      </div>
    </PlasmicLink__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTechTile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTechTile__VariantsArgs;
    args?: PlasmicTechTile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTechTile__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTechTile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTechTile__ArgProps,
          internalVariantPropNames: PlasmicTechTile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTechTile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTechTile";
  } else {
    func.displayName = `PlasmicTechTile.${nodeName}`;
  }
  return func;
}

export const PlasmicTechTile = Object.assign(
  // Top-level PlasmicTechTile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTechTile
    internalVariantProps: PlasmicTechTile__VariantProps,
    internalArgProps: PlasmicTechTile__ArgProps
  }
);

export default PlasmicTechTile;
/* prettier-ignore-end */
