/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: ydgBLCRsK_6P

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import GlobalShell from "../../GlobalShell"; // plasmic-import: VYweC3w_Jh99/component
import Section from "../../Section"; // plasmic-import: FaKfIdG9aMZc/component
import Hero from "../../Hero"; // plasmic-import: 6HGOGZ6Em2sv/component
import HypernovaButton from "../../HypernovaButton"; // plasmic-import: dBZzdq8VzYgG/component
import BlurbCard from "../../BlurbCard"; // plasmic-import: AS_J8BsUuYTm/component
import InfoCard from "../../InfoCard"; // plasmic-import: G0Ap6CzAQ22G/component
import TechnologyList from "../../TechnologyList"; // plasmic-import: qMedUY4rzZf9/component
import Footer from "../../Footer"; // plasmic-import: XJ7-8nUHEe46/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicProductionQuality.module.css"; // plasmic-import: ydgBLCRsK_6P/css

import Icon46Icon from "./icons/PlasmicIcon__Icon46"; // plasmic-import: 5nfb_9p9ple9/icon
import Icon71Icon from "./icons/PlasmicIcon__Icon71"; // plasmic-import: 3HJ2LylcNLxX/icon
import Icon72Icon from "./icons/PlasmicIcon__Icon72"; // plasmic-import: ZFs9QHeqjs9o/icon
import Icon73Icon from "./icons/PlasmicIcon__Icon73"; // plasmic-import: IbV6XjeF7v4q/icon
import Icon74Icon from "./icons/PlasmicIcon__Icon74"; // plasmic-import: JMSZX20zR7i5/icon
import Icon76Icon from "./icons/PlasmicIcon__Icon76"; // plasmic-import: w5DPorfxmZZf/icon
import Icon75Icon from "./icons/PlasmicIcon__Icon75"; // plasmic-import: 1QxHE4vDx658/icon
import Icon77Icon from "./icons/PlasmicIcon__Icon77"; // plasmic-import: dlCzBjKs2XHq/icon
import Icon79Icon from "./icons/PlasmicIcon__Icon79"; // plasmic-import: XObYFoACuXwf/icon
import Icon31Icon from "./icons/PlasmicIcon__Icon31"; // plasmic-import: WTHf47GHZTrx/icon
import Icon48Icon from "./icons/PlasmicIcon__Icon48"; // plasmic-import: aA_Cd9_TlWLs/icon

createPlasmicElementProxy;

export type PlasmicProductionQuality__VariantMembers = {};
export type PlasmicProductionQuality__VariantsArgs = {};
type VariantPropType = keyof PlasmicProductionQuality__VariantsArgs;
export const PlasmicProductionQuality__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProductionQuality__ArgsType = {};
type ArgPropType = keyof PlasmicProductionQuality__ArgsType;
export const PlasmicProductionQuality__ArgProps = new Array<ArgPropType>();

export type PlasmicProductionQuality__OverridesType = {
  root?: Flex__<"div">;
  globalShell?: Flex__<typeof GlobalShell>;
  hero?: Flex__<typeof Section>;
  whyVibecodedBreaks?: Flex__<typeof Section>;
  h2?: Flex__<"h2">;
  blurbCard?: Flex__<typeof BlurbCard>;
  howWeDoIt?: Flex__<typeof Section>;
  techStack?: Flex__<typeof Section>;
  technologyList?: Flex__<typeof TechnologyList>;
  hypernovaDifferentiators?: Flex__<typeof Section>;
};

export interface DefaultProductionQualityProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProductionQuality__RenderFunc(props: {
  variants: PlasmicProductionQuality__VariantsArgs;
  args: PlasmicProductionQuality__ArgsType;
  overrides: PlasmicProductionQuality__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicProductionQuality.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicProductionQuality.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicProductionQuality.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicProductionQuality.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicProductionQuality.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicProductionQuality.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicProductionQuality.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicProductionQuality.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <GlobalShell
            data-plasmic-name={"globalShell"}
            data-plasmic-override={overrides.globalShell}
            className={classNames("__wab_instance", sty.globalShell)}
            main={
              <div className={classNames(projectcss.all, sty.freeBox__dhHl4)}>
                <Section
                  data-plasmic-name={"hero"}
                  data-plasmic-override={overrides.hero}
                  bgImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__xPtQk)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? {
                              src: "/plasmic/hypernova_inc/images/group221Png.png",
                              fullWidth: 430,
                              fullHeight: 1344,
                              aspectRatio: undefined
                            }
                          : {
                              src: "/plasmic/hypernova_inc/images/group2181Png.png",
                              fullWidth: 1920,
                              fullHeight: 1075,
                              aspectRatio: undefined
                            }
                      }
                    />
                  }
                  className={classNames("__wab_instance", sty.hero)}
                  sectionContent={
                    <Hero
                      buttons={
                        <React.Fragment>
                          <HypernovaButton
                            className={classNames(
                              "__wab_instance",
                              sty.hypernovaButton__ymgNn
                            )}
                            destination={"tel:8884977682"}
                            padding={"_1330"}
                            slot={
                              <Icon46Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__uc3Ee
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__zHog9
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__maTz0
                                )}
                              >
                                {"Talk to Our Team"}
                              </div>
                            </div>
                          </HypernovaButton>
                          <HypernovaButton
                            className={classNames(
                              "__wab_instance",
                              sty.hypernovaButton__kNSjo
                            )}
                            color={"blueOutline"}
                            destination={`/book-a-meeting`}
                            iconPosition={"none"}
                            padding={"_1330"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__th5Ok
                              )}
                            >
                              {"Upgrade Your App"}
                            </div>
                          </HypernovaButton>
                        </React.Fragment>
                      }
                      className={classNames("__wab_instance", sty.hero__uzvhH)}
                      description={
                        "AI can spark an idea. But only senior engineers can turn that idea into a production quality product."
                      }
                      heading={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eOjfA
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"When "}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-CtevabluNWTZ)" }}
                            >
                              {"Vibe Coded Apps"}
                            </span>
                            <React.Fragment>
                              {
                                " Hit Their Limit, We Take You the Rest of the Way"
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                      }
                      socialProofDisabled={true}
                      subheadingDisabled={true}
                    />
                  }
                />

                <Section
                  data-plasmic-name={"whyVibecodedBreaks"}
                  data-plasmic-override={overrides.whyVibecodedBreaks}
                  backgroundDisabled={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : undefined
                  }
                  bgImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__efq3J)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hypernova_inc/images/group219Png.png",
                        fullWidth: 1313,
                        fullHeight: 931,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.whyVibecodedBreaks
                  )}
                  h2={null}
                  header={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? undefined
                      : true
                  }
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jPnE2)}
                    >
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          sty.h2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rSm5I
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>
                              {"Why Vibe-Coded Apps "}
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-CtevabluNWTZ)" }}
                            >
                              {"Break Under Real Use Issues"}
                            </span>
                          </React.Fragment>
                        </div>
                      </h2>
                      <BlurbCard
                        data-plasmic-name={"blurbCard"}
                        data-plasmic-override={overrides.blurbCard}
                        className={classNames("__wab_instance", sty.blurbCard)}
                        primary={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__eO7N
                            )}
                          >
                            {
                              "Large language models often generate functions, classes, or library names that don\u2019t actually exist. Even top models continue to hallucinate under uncertainty. (See \u201cWhy Language Models Hallucinate,\u201d arXiv)\u00b9"
                            }
                          </div>
                        }
                        title={"Hallucinated or Confabulated Code"}
                      />
                    </div>
                  }
                />

                <Section
                  data-plasmic-name={"howWeDoIt"}
                  data-plasmic-override={overrides.howWeDoIt}
                  backgroundDisabled={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? undefined
                      : undefined
                  }
                  bgImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__lm3GA)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/hypernova_inc/images/group1371Png.png",
                        fullWidth: 1920,
                        fullHeight: 1705,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  className={classNames("__wab_instance", sty.howWeDoIt)}
                  h2={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jupol
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"Convert Vibe Code to "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-CtevabluNWTZ)" }}
                        >
                          {"Production:"}
                        </span>
                      </React.Fragment>
                    </div>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__d7Bvx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__n43Jj
                        )}
                      >
                        <InfoCard
                          className={classNames(
                            "__wab_instance",
                            sty.infoCard__hl2Qf
                          )}
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jT8Nm
                              )}
                            >
                              {
                                "We review your existing code, architecture, dependencies, and security posture."
                              }
                            </div>
                          }
                          hasDescription={true}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__u3Ai1
                              )}
                            >
                              {"Audit & Assessment"}
                            </div>
                          }
                        >
                          <Icon71Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___1Rurf
                            )}
                            role={"img"}
                          />
                        </InfoCard>
                        <InfoCard
                          className={classNames(
                            "__wab_instance",
                            sty.infoCard__qCMl
                          )}
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__pbC7H
                              )}
                            >
                              {
                                "Move secrets to vaults, patch vulnerabilities, enforce authentication and authorization."
                              }
                            </div>
                          }
                          hasDescription={true}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__r6U8L
                              )}
                            >
                              {"Stabilize & Secure"}
                            </div>
                          }
                        >
                          <Icon72Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__abd66
                            )}
                            role={"img"}
                          />
                        </InfoCard>
                        <InfoCard
                          className={classNames(
                            "__wab_instance",
                            sty.infoCard__ePMt
                          )}
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__boVk6
                              )}
                            >
                              {
                                " Introduce modular structure, \nCI/CD, infrastructure patterns, observability"
                              }
                            </div>
                          }
                          hasDescription={true}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__sey2J
                              )}
                            >
                              {"Re-Architect for Scale"}
                            </div>
                          }
                        >
                          <Icon73Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___5TpCo
                            )}
                            role={"img"}
                          />
                        </InfoCard>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__w85VI
                        )}
                      >
                        <InfoCard
                          className={classNames(
                            "__wab_instance",
                            sty.infoCard__an9Jt
                          )}
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__cJrC
                              )}
                            >
                              {
                                "Add test coverage, QA cycles, regression tests, performance validation."
                              }
                            </div>
                          }
                          hasDescription={true}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__pYoRb
                              )}
                            >
                              {"Test & Validate"}
                            </div>
                          }
                        >
                          <Icon74Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___0EyN
                            )}
                            role={"img"}
                          />
                        </InfoCard>
                        <InfoCard
                          className={classNames(
                            "__wab_instance",
                            sty.infoCard__lofLe
                          )}
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fEmJr
                              )}
                            >
                              {
                                "Use AI tools for speed, under \nsenior developer oversight and validation."
                              }
                            </div>
                          }
                          hasDescription={true}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xu26F
                              )}
                            >
                              {"Enhance with AI (Safely) & Secure"}
                            </div>
                          }
                        >
                          <Icon76Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xViGj
                            )}
                            role={"img"}
                          />
                        </InfoCard>
                        <InfoCard
                          className={classNames(
                            "__wab_instance",
                            sty.infoCard__xwG2V
                          )}
                          description={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___019D6
                              )}
                            >
                              {
                                "Launch with monitoring, maintenance, rollback strategies, and ongoing iteration."
                              }
                            </div>
                          }
                          hasDescription={true}
                          slot={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gbJsR
                              )}
                            >
                              {"Deploy & Support"}
                            </div>
                          }
                        >
                          <Icon75Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vGyN3
                            )}
                            role={"img"}
                          />
                        </InfoCard>
                      </div>
                    </div>
                  }
                />

                <Section
                  data-plasmic-name={"techStack"}
                  data-plasmic-override={overrides.techStack}
                  backgroundDisabled={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  }
                  bgImage={null}
                  className={classNames("__wab_instance", sty.techStack)}
                  h2={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kZOc
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"Built with Tools You "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-CtevabluNWTZ)" }}
                        >
                          {"Trust "}
                        </span>
                      </React.Fragment>
                    </div>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7BMRu
                      )}
                    >
                      <TechnologyList
                        data-plasmic-name={"technologyList"}
                        data-plasmic-override={overrides.technologyList}
                        className={classNames(
                          "__wab_instance",
                          sty.technologyList
                        )}
                      />
                    </div>
                  }
                />

                <Section
                  data-plasmic-name={"hypernovaDifferentiators"}
                  data-plasmic-override={overrides.hypernovaDifferentiators}
                  backgroundDisabled={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.hypernovaDifferentiators
                  )}
                  h2={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jSdRc
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Why Choose "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-CtevabluNWTZ)" }}
                        >
                          {"hypernova"}
                        </span>
                        <React.Fragment>
                          {" Key Differentiators:"}
                        </React.Fragment>
                      </React.Fragment>
                    </div>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cbhX)}
                    >
                      <InfoCard
                        background={"none"}
                        className={classNames(
                          "__wab_instance",
                          sty.infoCard___88Wrn
                        )}
                        iconPosition={"topLeft"}
                        iconSize={"_60Px"}
                        slot={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rWgpb
                            )}
                          >
                            {"100% U.S. \nbased senior engineers"}
                          </div>
                        }
                      >
                        <Icon77Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___0S9FT
                          )}
                          role={"img"}
                        />
                      </InfoCard>
                      <InfoCard
                        background={"none"}
                        className={classNames(
                          "__wab_instance",
                          sty.infoCard__btAf9
                        )}
                        iconPosition={"topLeft"}
                        iconSize={"_60Px"}
                        slot={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__epa88
                            )}
                          >
                            {"Teams with \nprior shared experience"}
                          </div>
                        }
                      >
                        <Icon79Icon
                          className={classNames(projectcss.all, sty.svg__yJm3O)}
                          role={"img"}
                        />
                      </InfoCard>
                      <InfoCard
                        background={"none"}
                        className={classNames(
                          "__wab_instance",
                          sty.infoCard__dWu4M
                        )}
                        iconPosition={"topLeft"}
                        iconSize={"_60Px"}
                        slot={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3YYf
                            )}
                          >
                            {"AI-augmented workflows that preserve correctness"}
                          </div>
                        }
                      >
                        <Icon31Icon
                          className={classNames(projectcss.all, sty.svg__fxPes)}
                          role={"img"}
                        />
                      </InfoCard>
                      <InfoCard
                        background={"none"}
                        className={classNames(
                          "__wab_instance",
                          sty.infoCard__fGuOj
                        )}
                        iconPosition={"topLeft"}
                        iconSize={"_60Px"}
                        slot={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jGbyF
                            )}
                          >
                            {"Clear communication with no offshore risk"}
                          </div>
                        }
                      >
                        <Icon48Icon
                          className={classNames(projectcss.all, sty.svg__npYgb)}
                          role={"img"}
                        />
                      </InfoCard>
                    </div>
                  }
                />
              </div>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "globalShell",
    "hero",
    "whyVibecodedBreaks",
    "h2",
    "blurbCard",
    "howWeDoIt",
    "techStack",
    "technologyList",
    "hypernovaDifferentiators"
  ],
  globalShell: [
    "globalShell",
    "hero",
    "whyVibecodedBreaks",
    "h2",
    "blurbCard",
    "howWeDoIt",
    "techStack",
    "technologyList",
    "hypernovaDifferentiators"
  ],
  hero: ["hero"],
  whyVibecodedBreaks: ["whyVibecodedBreaks", "h2", "blurbCard"],
  h2: ["h2"],
  blurbCard: ["blurbCard"],
  howWeDoIt: ["howWeDoIt"],
  techStack: ["techStack", "technologyList"],
  technologyList: ["technologyList"],
  hypernovaDifferentiators: ["hypernovaDifferentiators"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  globalShell: typeof GlobalShell;
  hero: typeof Section;
  whyVibecodedBreaks: typeof Section;
  h2: "h2";
  blurbCard: typeof BlurbCard;
  howWeDoIt: typeof Section;
  techStack: typeof Section;
  technologyList: typeof TechnologyList;
  hypernovaDifferentiators: typeof Section;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProductionQuality__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProductionQuality__VariantsArgs;
    args?: PlasmicProductionQuality__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicProductionQuality__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicProductionQuality__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProductionQuality__ArgProps,
          internalVariantPropNames: PlasmicProductionQuality__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProductionQuality__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductionQuality";
  } else {
    func.displayName = `PlasmicProductionQuality.${nodeName}`;
  }
  return func;
}

export const PlasmicProductionQuality = Object.assign(
  // Top-level PlasmicProductionQuality renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    globalShell: makeNodeComponent("globalShell"),
    hero: makeNodeComponent("hero"),
    whyVibecodedBreaks: makeNodeComponent("whyVibecodedBreaks"),
    h2: makeNodeComponent("h2"),
    blurbCard: makeNodeComponent("blurbCard"),
    howWeDoIt: makeNodeComponent("howWeDoIt"),
    techStack: makeNodeComponent("techStack"),
    technologyList: makeNodeComponent("technologyList"),
    hypernovaDifferentiators: makeNodeComponent("hypernovaDifferentiators"),

    // Metadata about props expected for PlasmicProductionQuality
    internalVariantProps: PlasmicProductionQuality__VariantProps,
    internalArgProps: PlasmicProductionQuality__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "hypernova | Convert Vibe Code to Production Quality",
      description:
        "Turn your AI-generated prototype into a production-quality application. hypernova’s U.S. based developers transform vibe-coded projects into secure, scalable, and high-performance software built to last. How to turn your vibe code into production quality!",
      ogImageSrc:
        "https://site-assets.plasmic.app/88d01449a0117112c7b7bb59aec0c0a6.jpg",
      canonical: ""
    }
  }
);

export default PlasmicProductionQuality;
/* prettier-ignore-end */
