/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: kCDrgVKRroz8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import GlobalShell from "../../GlobalShell"; // plasmic-import: VYweC3w_Jh99/component
import Section from "../../Section"; // plasmic-import: FaKfIdG9aMZc/component
import Hero from "../../Hero"; // plasmic-import: 6HGOGZ6Em2sv/component
import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import BlurbCard from "../../BlurbCard"; // plasmic-import: AS_J8BsUuYTm/component
import FeaturesCard from "../../FeaturesCard"; // plasmic-import: WPZJuBWNQ9vc/component
import TechnologyList from "../../TechnologyList"; // plasmic-import: qMedUY4rzZf9/component
import Footer from "../../Footer"; // plasmic-import: XJ7-8nUHEe46/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicNova.module.css"; // plasmic-import: kCDrgVKRroz8/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: k4QR0HpbesmK/icon
import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: UosIBoZBJdWT/icon
import Icon48Icon from "./icons/PlasmicIcon__Icon48"; // plasmic-import: aA_Cd9_TlWLs/icon
import Icon82Icon from "./icons/PlasmicIcon__Icon82"; // plasmic-import: waID8GTGCvhO/icon
import Icon80Icon from "./icons/PlasmicIcon__Icon80"; // plasmic-import: uLvNeD_CMKtn/icon

createPlasmicElementProxy;

export type PlasmicNova__VariantMembers = {};
export type PlasmicNova__VariantsArgs = {};
type VariantPropType = keyof PlasmicNova__VariantsArgs;
export const PlasmicNova__VariantProps = new Array<VariantPropType>();

export type PlasmicNova__ArgsType = {};
type ArgPropType = keyof PlasmicNova__ArgsType;
export const PlasmicNova__ArgProps = new Array<ArgPropType>();

export type PlasmicNova__OverridesType = {
  root?: Flex__<"div">;
  globalShell?: Flex__<typeof GlobalShell>;
  hero?: Flex__<typeof Section>;
  whyNova?: Flex__<typeof Section>;
  blurbCard?: Flex__<typeof BlurbCard>;
  novaFeatures?: Flex__<typeof Section>;
  howWeBuiltIt?: Flex__<typeof Section>;
  technologyList?: Flex__<typeof TechnologyList>;
};

export interface DefaultNovaProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNova__RenderFunc(props: {
  variants: PlasmicNova__VariantsArgs;
  args: PlasmicNova__ArgsType;
  overrides: PlasmicNova__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicNova.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicNova.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicNova.pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={PlasmicNova.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicNova.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={PlasmicNova.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicNova.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicNova.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <GlobalShell
            data-plasmic-name={"globalShell"}
            data-plasmic-override={overrides.globalShell}
            className={classNames("__wab_instance", sty.globalShell)}
            main={
              <div className={classNames(projectcss.all, sty.freeBox__onT5R)}>
                <Section
                  data-plasmic-name={"hero"}
                  data-plasmic-override={overrides.hero}
                  backgroundDisabled={true}
                  bgImage={null}
                  className={classNames("__wab_instance", sty.hero)}
                  sectionContent={
                    <React.Fragment>
                      <Hero
                        className={classNames(
                          "__wab_instance",
                          sty.hero__tyNpB
                        )}
                        description={
                          "A simple, human way to talk to AI. \nType, speak, and capture every detail effortlessly."
                        }
                        heading={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__oQjGi
                            )}
                          >
                            <h1
                              className={classNames(
                                projectcss.all,
                                projectcss.h1,
                                sty.h1__y2KLj
                              )}
                            >
                              <h1
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h1,
                                  projectcss.__wab_text,
                                  sty.h1__hOjvT
                                )}
                              >
                                {"Nova by hypernova"}
                              </h1>
                            </h1>
                            <h1
                              className={classNames(
                                projectcss.all,
                                projectcss.h1,
                                projectcss.__wab_text,
                                sty.h1__plBxo
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>
                                  {"The Future of "}
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "var(--token-CtevabluNWTZ)" }}
                                >
                                  {"AI Conversations"}
                                </span>
                              </React.Fragment>
                            </h1>
                          </div>
                        }
                        socialProofDisabled={true}
                        subheadingDisabled={true}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__fZhv)}
                        displayHeight={"auto"}
                        displayMaxHeight={"667px"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/hypernova_inc/images/image39.png",
                          fullWidth: 2180,
                          fullHeight: 1334,
                          aspectRatio: undefined
                        }}
                      />
                    </React.Fragment>
                  }
                />

                <Section
                  data-plasmic-name={"whyNova"}
                  data-plasmic-override={overrides.whyNova}
                  backgroundDisabled={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? undefined
                      : undefined
                  }
                  bgImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__t6Dzk)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? {
                              src: "/plasmic/hypernova_inc/images/group193Png.png",
                              fullWidth: 430,
                              fullHeight: 693,
                              aspectRatio: undefined
                            }
                          : {
                              src: "/plasmic/hypernova_inc/images/group225Png.png",
                              fullWidth: 1920,
                              fullHeight: 2315,
                              aspectRatio: undefined
                            }
                      }
                    />
                  }
                  className={classNames("__wab_instance", sty.whyNova)}
                  h2={null}
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__j4Ei5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kyMf
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            sty.h2__h1YF
                          )}
                        >
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2___2VPcX
                            )}
                          >
                            {"Why Nova?"}
                          </h2>
                        </h2>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__l3I1
                          )}
                        >
                          {
                            "Stop juggling between tools. Nova brings text chat, voice conversations, and transcripts together in one place \u2014 so your team can focus on ideas, not logistics."
                          }
                        </div>
                        <BlurbCard
                          data-plasmic-name={"blurbCard"}
                          data-plasmic-override={overrides.blurbCard}
                          className={classNames(
                            "__wab_instance",
                            sty.blurbCard
                          )}
                          primary={
                            "With Nova, we promise clarity, simplicity, and accuracy \u2014 all in a secure, intuitive AI experience that helps you work smarter every day."
                          }
                        />
                      </div>
                    </div>
                  }
                />

                <Section
                  data-plasmic-name={"novaFeatures"}
                  data-plasmic-override={overrides.novaFeatures}
                  bgImage={
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0LVLo
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__fkldn)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? {
                                src: "/plasmic/hypernova_inc/images/group183Png.png",
                                fullWidth: 430,
                                fullHeight: 2054,
                                aspectRatio: undefined
                              }
                            : {
                                src: "/plasmic/hypernova_inc/images/frame252Png.png",
                                fullWidth: 1920,
                                fullHeight: 1406,
                                aspectRatio: undefined
                              }
                        }
                      />
                    </div>
                  }
                  className={classNames("__wab_instance", sty.novaFeatures)}
                  h2={
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2___2WaSk
                      )}
                    >
                      {"Nova Features"}
                    </h2>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__oLh1F)}
                    >
                      <FeaturesCard
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kkoMf
                            )}
                          >
                            {
                              "Fast, precise answers in a clean interface. Save conversations and share them with your team."
                            }
                          </div>
                        }
                        icon={
                          <Icon48Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__gChSv
                            )}
                            role={"img"}
                          />
                        }
                        title={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__cs5Cy
                            )}
                          >
                            {"Chat by Typing"}
                          </h3>
                        }
                      />

                      <FeaturesCard
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qIrrj
                            )}
                          >
                            {
                              "Talk naturally, interrupt whenever you need, and let Nova keep the flow going."
                            }
                          </div>
                        }
                        icon={
                          <Icon82Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__p8SXq
                            )}
                            role={"img"}
                          />
                        }
                        title={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__e3EfP
                            )}
                          >
                            {"Interactive Voice Chat"}
                          </h3>
                        }
                      />

                      <FeaturesCard
                        description={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yEqg3
                            )}
                          >
                            {
                              "Record calls and get accurate, speaker-labeled transcripts you can search, share, and export."
                            }
                          </div>
                        }
                        icon={
                          <Icon80Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__iGzzQ
                            )}
                            role={"img"}
                          />
                        }
                        title={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__l5J5Y
                            )}
                          >
                            {"Voice-to-Text Transcription"}
                          </h3>
                        }
                      />
                    </div>
                  }
                  subheaderEnabled={true}
                  subheading={
                    "We combine human expertise with AI-driven efficiency to build enterprise-grade software that scales\u2014without the overhead of an in-house team."
                  }
                />

                <Section
                  data-plasmic-name={"howWeBuiltIt"}
                  data-plasmic-override={overrides.howWeBuiltIt}
                  backgroundDisabled={true}
                  className={classNames("__wab_instance", sty.howWeBuiltIt)}
                  h2={
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__cmx36
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"How we "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "var(--token-CtevabluNWTZ)" }}
                        >
                          {"built it."}
                        </span>
                      </React.Fragment>
                    </h2>
                  }
                  header={true}
                  sectionContent={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ttwxV)}
                    >
                      <TechnologyList
                        data-plasmic-name={"technologyList"}
                        data-plasmic-override={overrides.technologyList}
                        className={classNames(
                          "__wab_instance",
                          sty.technologyList
                        )}
                        useCase={"nova"}
                      />
                    </div>
                  }
                  subheading={
                    "We combine human expertise with AI-driven efficiency to build enterprise-grade software that scales\u2014without the overhead of an in-house team."
                  }
                />
              </div>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "globalShell",
    "hero",
    "whyNova",
    "blurbCard",
    "novaFeatures",
    "howWeBuiltIt",
    "technologyList"
  ],
  globalShell: [
    "globalShell",
    "hero",
    "whyNova",
    "blurbCard",
    "novaFeatures",
    "howWeBuiltIt",
    "technologyList"
  ],
  hero: ["hero"],
  whyNova: ["whyNova", "blurbCard"],
  blurbCard: ["blurbCard"],
  novaFeatures: ["novaFeatures"],
  howWeBuiltIt: ["howWeBuiltIt", "technologyList"],
  technologyList: ["technologyList"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  globalShell: typeof GlobalShell;
  hero: typeof Section;
  whyNova: typeof Section;
  blurbCard: typeof BlurbCard;
  novaFeatures: typeof Section;
  howWeBuiltIt: typeof Section;
  technologyList: typeof TechnologyList;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNova__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNova__VariantsArgs;
    args?: PlasmicNova__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNova__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNova__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNova__ArgProps,
          internalVariantPropNames: PlasmicNova__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNova__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNova";
  } else {
    func.displayName = `PlasmicNova.${nodeName}`;
  }
  return func;
}

export const PlasmicNova = Object.assign(
  // Top-level PlasmicNova renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    globalShell: makeNodeComponent("globalShell"),
    hero: makeNodeComponent("hero"),
    whyNova: makeNodeComponent("whyNova"),
    blurbCard: makeNodeComponent("blurbCard"),
    novaFeatures: makeNodeComponent("novaFeatures"),
    howWeBuiltIt: makeNodeComponent("howWeBuiltIt"),
    technologyList: makeNodeComponent("technologyList"),

    // Metadata about props expected for PlasmicNova
    internalVariantProps: PlasmicNova__VariantProps,
    internalArgProps: PlasmicNova__ArgProps,

    // Key-value metadata
    metadata: { robots: "noindex, nofollow" },

    // Page metadata
    pageMetadata: {
      title: "Nova by hypernova | AI Powered Voice and Chat Application",
      description:
        "See how hypernova built Nova using Plasmic, AWS Bedrock, AWS Amplify, AWS Cognito, AWS Polly, AWS Transcribe, and Claude. A showcase of our real time AI engineering and full stack capabilities.",
      ogImageSrc:
        "https://site-assets.plasmic.app/24c8523d1fbfc74ddcec922c8c20dd84.png",
      canonical: ""
    }
  }
);

export default PlasmicNova;
/* prettier-ignore-end */
