/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6
// Component: H-_o4Ye8qC3P

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HypernovaLinkButton from "../../HypernovaLinkButton"; // plasmic-import: dBZzdq8VzYgG/component
import ContactForm from "../../ContactForm"; // plasmic-import: hP0qyrwRZoNJ/component
import GradientAtmosphere from "../../GradientAtmosphere"; // plasmic-import: QTTe92wC06bw/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: j5F6xK8wcYv3Lu1Z2yvnp6/projectcss
import sty from "./PlasmicBookMeeting.module.css"; // plasmic-import: H-_o4Ye8qC3P/css

import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: UosIBoZBJdWT/icon

createPlasmicElementProxy;

export type PlasmicBookMeeting__VariantMembers = {};
export type PlasmicBookMeeting__VariantsArgs = {};
type VariantPropType = keyof PlasmicBookMeeting__VariantsArgs;
export const PlasmicBookMeeting__VariantProps = new Array<VariantPropType>();

export type PlasmicBookMeeting__ArgsType = {};
type ArgPropType = keyof PlasmicBookMeeting__ArgsType;
export const PlasmicBookMeeting__ArgProps = new Array<ArgPropType>();

export type PlasmicBookMeeting__OverridesType = {
  root?: Flex__<"div">;
  content?: Flex__<"div">;
  contact?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  hypernovaLinkButton?: Flex__<typeof HypernovaLinkButton>;
  svg?: Flex__<"svg">;
  contactForm?: Flex__<typeof ContactForm>;
  background?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultBookMeetingProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBookMeeting__RenderFunc(props: {
  variants: PlasmicBookMeeting__VariantsArgs;
  args: PlasmicBookMeeting__ArgsType;
  overrides: PlasmicBookMeeting__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"content"}
        data-plasmic-override={overrides.content}
        className={classNames(projectcss.all, sty.content)}
      >
        <div
          data-plasmic-name={"contact"}
          data-plasmic-override={overrides.contact}
          className={classNames(projectcss.all, sty.contact)}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__odVjE
              )}
            >
              <React.Fragment>
                <React.Fragment>{"We're here for "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontStyle: "italic" }}
                >
                  {"you"}
                </span>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xyjrt
              )}
            >
              {
                "Not sure where to begin or just want to talk it through? We\u2019re happy to help. Whether it\u2019s a rough idea, a specific requirement, or just a quick question."
              }
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fsH4I
              )}
            >
              <React.Fragment>
                <React.Fragment>{"Rather receive an "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontStyle: "italic" }}
                >
                  {"instant"}
                </span>
                <React.Fragment> </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "var(--token-CtevabluNWTZ)" }}
                >
                  {"AI Powered"}
                </span>
                <React.Fragment>{" estimate instead?"}</React.Fragment>
              </React.Fragment>
            </div>
            <HypernovaLinkButton
              data-plasmic-name={"hypernovaLinkButton"}
              data-plasmic-override={overrides.hypernovaLinkButton}
              className={classNames("__wab_instance", sty.hypernovaLinkButton)}
              color={"blueOutline"}
              destination={`/tools/ai-project-estimator#${"project-estimator"}`}
              iconPosition={"right"}
              padding={"_1330"}
              slot={
                <VectorSvgIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__byTd5
                )}
              >
                {"Get an Instant Estimate"}
              </div>
            </HypernovaLinkButton>
          </div>
          <ContactForm
            data-plasmic-name={"contactForm"}
            data-plasmic-override={overrides.contactForm}
            className={classNames("__wab_instance", sty.contactForm)}
          />
        </div>
      </div>
      {false ? (
        <div
          data-plasmic-name={"background"}
          data-plasmic-override={overrides.background}
          className={classNames(projectcss.all, sty.background)}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "none"
                : "100%"
            }
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "auto"
                : "100%"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/hypernova_inc/images/frame224Png.png",
              fullWidth: 1920,
              fullHeight: 1203,
              aspectRatio: undefined
            }}
          />

          <GradientAtmosphere
            className={classNames(
              "__wab_instance",
              sty.gradientAtmosphere__wFjF
            )}
          />

          <GradientAtmosphere
            className={classNames(
              "__wab_instance",
              sty.gradientAtmosphere__rlWdH
            )}
          />
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "content",
    "contact",
    "freeBox",
    "hypernovaLinkButton",
    "svg",
    "contactForm",
    "background",
    "img"
  ],
  content: [
    "content",
    "contact",
    "freeBox",
    "hypernovaLinkButton",
    "svg",
    "contactForm"
  ],
  contact: ["contact", "freeBox", "hypernovaLinkButton", "svg", "contactForm"],
  freeBox: ["freeBox", "hypernovaLinkButton", "svg"],
  hypernovaLinkButton: ["hypernovaLinkButton", "svg"],
  svg: ["svg"],
  contactForm: ["contactForm"],
  background: ["background", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  content: "div";
  contact: "div";
  freeBox: "div";
  hypernovaLinkButton: typeof HypernovaLinkButton;
  svg: "svg";
  contactForm: typeof ContactForm;
  background: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBookMeeting__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBookMeeting__VariantsArgs;
    args?: PlasmicBookMeeting__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicBookMeeting__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicBookMeeting__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBookMeeting__ArgProps,
          internalVariantPropNames: PlasmicBookMeeting__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBookMeeting__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBookMeeting";
  } else {
    func.displayName = `PlasmicBookMeeting.${nodeName}`;
  }
  return func;
}

export const PlasmicBookMeeting = Object.assign(
  // Top-level PlasmicBookMeeting renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    content: makeNodeComponent("content"),
    contact: makeNodeComponent("contact"),
    freeBox: makeNodeComponent("freeBox"),
    hypernovaLinkButton: makeNodeComponent("hypernovaLinkButton"),
    svg: makeNodeComponent("svg"),
    contactForm: makeNodeComponent("contactForm"),
    background: makeNodeComponent("background"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicBookMeeting
    internalVariantProps: PlasmicBookMeeting__VariantProps,
    internalArgProps: PlasmicBookMeeting__ArgProps
  }
);

export default PlasmicBookMeeting;
/* prettier-ignore-end */
