/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j5F6xK8wcYv3Lu1Z2yvnp6

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsy0FRnvcymXhk } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: y0FRnvcymXHK/globalVariant
import {
  ThreeJsAstronautValue,
  useThreeJsAstronaut
} from "./PlasmicGlobalVariant__ThreeJsAstronaut"; // plasmic-import: fktnqh3Xq4lt/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsy0FRnvcymXhk,
  threeJsAstronaut: useThreeJsAstronaut
});
